# Generated by Django 5.2.15 on 2026-09-22 19:23

import apps.saas_tenants.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ConviteDelegacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito'), ('recusado', 'Recusado')], default='pendente', max_length=10)),
                ('justificativa_recusa', models.TextField(blank=True)),
                ('object_id', models.PositiveIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('respondido_em', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('delegante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convites_delegacao_enviados', to=settings.AUTH_USER_MODEL)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_delegacao_recebidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Convite de delegação',
                'verbose_name_plural': 'Convites de delegação',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PapelAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('codigo_preset', models.SlugField(blank=True, help_text='Identificador técnico estável dos presets de fábrica. Nulo para papéis personalizados pelo Tenant Admin.', null=True, verbose_name='Código de preset')),
                ('protegido_sistema', models.BooleanField(default=False, help_text='Presets de fábrica marcados aqui não podem ser excluídos nem ter o codigo_preset alterado pela interface.', verbose_name='Protegido pelo sistema')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Papel de Acesso',
                'verbose_name_plural': 'Papéis de Acesso',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(fields=('nome',), name='uniq_papelacesso_nome'), models.UniqueConstraint(condition=models.Q(('codigo_preset__isnull', False)), fields=('codigo_preset',), name='uniq_papelacesso_codigo_preset'), models.CheckConstraint(condition=models.Q(('codigo_preset__isnull', True), models.Q(('codigo_preset', ''), _negated=True), _connector='OR'), name='chk_papelacesso_codigo_preset_nao_vazio')],
            },
        ),
        migrations.CreateModel(
            name='HabilitacaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('processos', 'Processos'), ('clientes', 'Clientes'), ('financeiro', 'Financeiro'), ('tarefas', 'Tarefas'), ('modelos', 'Modelos de peças'), ('agenda', 'Agenda'), ('gerir', 'Gerir')], max_length=30, verbose_name='Módulo')),
                ('item', models.CharField(choices=[('processos_criar', 'Criar processo'), ('processos_editar', 'Editar processo'), ('processos_andamento_adicionar', 'Adicionar andamento'), ('processos_usar_ia', 'Usar assistência de IA'), ('processos_usar_laboratorio', 'Usar Laboratório Jurídico'), ('processos_atribuir_responsavel', 'Atribuir responsabilidade de processos'), ('processos_documento_adicionar', 'Adicionar documento ao processo'), ('processos_documento_excluir', 'Excluir documento do processo'), ('processos_excluir', 'Excluir processo definitivamente'), ('clientes_criar', 'Criar cliente'), ('clientes_editar', 'Editar cliente'), ('clientes_desativar', 'Desativar cliente'), ('clientes_reativar', 'Reativar cliente'), ('clientes_excluir', 'Excluir cliente definitivamente'), ('clientes_documento_adicionar', 'Adicionar documento ao cliente'), ('clientes_documento_excluir', 'Excluir documento do cliente'), ('tarefas_atribuir_outros', 'Atribuir tarefa a outros usuários'), ('modelos_criar', 'Criar modelo de peça'), ('modelos_editar_estilo', 'Editar estilo de peças'), ('modelos_editar_alheio', 'Editar modelo de peça de outro usuário'), ('modelos_excluir_alheio', 'Excluir modelo de peça de outro usuário'), ('modelos_gerir_categorias', 'Gerir tipos de peça'), ('agenda_criar_para_outros', 'Criar compromisso para outros usuários'), ('financeiro_reabrir_lancamento_pago', 'Reabrir lançamento gerado por solicitação paga'), ('gerir_criar_usuario', 'Criar usuário'), ('gerir_habilitar_usuario_processos', 'Habilitar usuário em processos'), ('gerir_criar_equipe', 'Criar equipe'), ('gerir_habilitar_terceiros', 'Habilitar terceiros')], max_length=60, verbose_name='Item')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilitacoes_individuais', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Habilitação Individual',
                'verbose_name_plural': 'Habilitações Individuais',
                'ordering': ['usuario', 'modulo', 'item'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'modulo', 'item'), name='uniq_habilitacaousuario_usuario_modulo_item'), models.CheckConstraint(condition=models.Q(models.Q(('item__in', ['processos_criar', 'processos_editar', 'processos_andamento_adicionar', 'processos_usar_ia', 'processos_usar_laboratorio', 'processos_atribuir_responsavel', 'processos_documento_adicionar', 'processos_documento_excluir', 'processos_excluir']), ('modulo', 'processos')), models.Q(('item__in', ['clientes_criar', 'clientes_editar', 'clientes_desativar', 'clientes_reativar', 'clientes_excluir', 'clientes_documento_adicionar', 'clientes_documento_excluir']), ('modulo', 'clientes')), models.Q(('item__in', ['tarefas_atribuir_outros']), ('modulo', 'tarefas')), models.Q(('item__in', ['modelos_criar', 'modelos_editar_estilo', 'modelos_editar_alheio', 'modelos_excluir_alheio', 'modelos_gerir_categorias']), ('modulo', 'modelos')), models.Q(('item__in', ['agenda_criar_para_outros']), ('modulo', 'agenda')), models.Q(('item__in', ['financeiro_reabrir_lancamento_pago']), ('modulo', 'financeiro')), models.Q(('item__in', ['gerir_criar_usuario', 'gerir_habilitar_usuario_processos', 'gerir_criar_equipe', 'gerir_habilitar_terceiros']), ('modulo', 'gerir')), _connector='OR'), name='chk_habilitacaousuario_modulo_item')],
            },
        ),
        migrations.CreateModel(
            name='MembroEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eh_gerente', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='accounts.equipe')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_equipe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membro de Equipe',
                'verbose_name_plural': 'Membros de Equipe',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'equipe'), name='uniq_usuario_equipe')],
            },
        ),
        migrations.CreateModel(
            name='HabilitacaoPapel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('processos', 'Processos'), ('clientes', 'Clientes'), ('financeiro', 'Financeiro'), ('tarefas', 'Tarefas'), ('modelos', 'Modelos de peças'), ('agenda', 'Agenda'), ('gerir', 'Gerir')], max_length=30, verbose_name='Módulo')),
                ('item', models.CharField(choices=[('processos_criar', 'Criar processo'), ('processos_editar', 'Editar processo'), ('processos_andamento_adicionar', 'Adicionar andamento'), ('processos_usar_ia', 'Usar assistência de IA'), ('processos_usar_laboratorio', 'Usar Laboratório Jurídico'), ('processos_atribuir_responsavel', 'Atribuir responsabilidade de processos'), ('processos_documento_adicionar', 'Adicionar documento ao processo'), ('processos_documento_excluir', 'Excluir documento do processo'), ('processos_excluir', 'Excluir processo definitivamente'), ('clientes_criar', 'Criar cliente'), ('clientes_editar', 'Editar cliente'), ('clientes_desativar', 'Desativar cliente'), ('clientes_reativar', 'Reativar cliente'), ('clientes_excluir', 'Excluir cliente definitivamente'), ('clientes_documento_adicionar', 'Adicionar documento ao cliente'), ('clientes_documento_excluir', 'Excluir documento do cliente'), ('tarefas_atribuir_outros', 'Atribuir tarefa a outros usuários'), ('modelos_criar', 'Criar modelo de peça'), ('modelos_editar_estilo', 'Editar estilo de peças'), ('modelos_editar_alheio', 'Editar modelo de peça de outro usuário'), ('modelos_excluir_alheio', 'Excluir modelo de peça de outro usuário'), ('modelos_gerir_categorias', 'Gerir tipos de peça'), ('agenda_criar_para_outros', 'Criar compromisso para outros usuários'), ('financeiro_reabrir_lancamento_pago', 'Reabrir lançamento gerado por solicitação paga'), ('gerir_criar_usuario', 'Criar usuário'), ('gerir_habilitar_usuario_processos', 'Habilitar usuário em processos'), ('gerir_criar_equipe', 'Criar equipe'), ('gerir_habilitar_terceiros', 'Habilitar terceiros')], max_length=60, verbose_name='Item')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('papel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habilitacoes', to='accounts.papelacesso', verbose_name='Papel')),
            ],
            options={
                'verbose_name': 'Habilitação por Papel',
                'verbose_name_plural': 'Habilitações por Papel',
                'ordering': ['papel', 'modulo', 'item'],
                'constraints': [models.UniqueConstraint(fields=('papel', 'modulo', 'item'), name='uniq_habilitacaopapel_papel_modulo_item'), models.CheckConstraint(condition=models.Q(models.Q(('item__in', ['processos_criar', 'processos_editar', 'processos_andamento_adicionar', 'processos_usar_ia', 'processos_usar_laboratorio', 'processos_atribuir_responsavel', 'processos_documento_adicionar', 'processos_documento_excluir', 'processos_excluir']), ('modulo', 'processos')), models.Q(('item__in', ['clientes_criar', 'clientes_editar', 'clientes_desativar', 'clientes_reativar', 'clientes_excluir', 'clientes_documento_adicionar', 'clientes_documento_excluir']), ('modulo', 'clientes')), models.Q(('item__in', ['tarefas_atribuir_outros']), ('modulo', 'tarefas')), models.Q(('item__in', ['modelos_criar', 'modelos_editar_estilo', 'modelos_editar_alheio', 'modelos_excluir_alheio', 'modelos_gerir_categorias']), ('modulo', 'modelos')), models.Q(('item__in', ['agenda_criar_para_outros']), ('modulo', 'agenda')), models.Q(('item__in', ['financeiro_reabrir_lancamento_pago']), ('modulo', 'financeiro')), models.Q(('item__in', ['gerir_criar_usuario', 'gerir_habilitar_usuario_processos', 'gerir_criar_equipe', 'gerir_habilitar_terceiros']), ('modulo', 'gerir')), _connector='OR'), name='chk_habilitacaopapel_modulo_item')],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(blank=True, max_length=255)),
                ('cargo', models.CharField(blank=True, help_text='Apenas descritivo. Não controla permissões.', max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, storage=apps.saas_tenants.storage.StorageProtegido(), upload_to=apps.saas_tenants.storage.CaminhoArquivoTenant('protegido', 'accounts/avatares'))),
                ('is_admin_escritorio', models.BooleanField(default=False, help_text='Indica se este usuário é administrador do escritório.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_admin_escritorio', True)), fields=('is_admin_escritorio',), name='uniq_perfil_tenant_admin')],
            },
        ),
        migrations.CreateModel(
            name='PermissaoPapel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('processos', 'Processos'), ('clientes', 'Clientes'), ('financeiro', 'Financeiro'), ('tarefas', 'Tarefas'), ('modelos', 'Modelos de peças'), ('chat', 'Chat'), ('painel', 'Painel'), ('agenda', 'Agenda'), ('gerir', 'Gerir')], max_length=30, verbose_name='Módulo')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('nivel', models.CharField(blank=True, choices=[('somente_seus', 'Somente os seus'), ('todos', 'Todos'), ('solicitacoes', 'Apenas solicitações'), ('dados_proprios', 'Dados — só os meus lançamentos'), ('dados_todos', 'Dados — todos os lançamentos')], default='', help_text='Vazio para módulos sem escopo de dados (chat, gerir).', max_length=30, verbose_name='Nível de acesso')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('papel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permissoes_modulo', to='accounts.papelacesso', verbose_name='Papel')),
            ],
            options={
                'verbose_name': 'Permissão por Papel',
                'verbose_name_plural': 'Permissões por Papel',
                'ordering': ['papel', 'modulo'],
                'constraints': [models.UniqueConstraint(fields=('papel', 'modulo'), name='uniq_permissaopapel_papel_modulo'), models.CheckConstraint(condition=models.Q(models.Q(('modulo__in', ['processos', 'clientes', 'tarefas', 'modelos', 'painel', 'agenda']), ('nivel__in', ['somente_seus', 'todos'])), models.Q(('modulo', 'financeiro'), ('nivel__in', ['solicitacoes', 'dados_proprios', 'dados_todos'])), models.Q(('modulo__in', ['chat', 'gerir']), ('nivel', '')), _connector='OR'), name='chk_permissaopapel_nivel')],
            },
        ),
        migrations.CreateModel(
            name='PermissaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('processos', 'Processos'), ('clientes', 'Clientes'), ('financeiro', 'Financeiro'), ('tarefas', 'Tarefas'), ('modelos', 'Modelos de peças'), ('chat', 'Chat'), ('painel', 'Painel'), ('agenda', 'Agenda'), ('gerir', 'Gerir')], max_length=30, verbose_name='Módulo')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('nivel', models.CharField(blank=True, choices=[('somente_seus', 'Somente os seus'), ('todos', 'Todos'), ('solicitacoes', 'Apenas solicitações'), ('dados_proprios', 'Dados — só os meus lançamentos'), ('dados_todos', 'Dados — todos os lançamentos')], default='', help_text='Vazio para módulos sem escopo de dados (chat, gerir).', max_length=30, verbose_name='Nível de acesso')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_individuais', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Permissão Individual',
                'verbose_name_plural': 'Permissões Individuais',
                'ordering': ['usuario', 'modulo'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'modulo'), name='uniq_permissaousuario_usuario_modulo'), models.CheckConstraint(condition=models.Q(models.Q(('modulo__in', ['processos', 'clientes', 'tarefas', 'modelos', 'painel', 'agenda']), ('nivel__in', ['somente_seus', 'todos'])), models.Q(('modulo', 'financeiro'), ('nivel__in', ['solicitacoes', 'dados_proprios', 'dados_todos'])), models.Q(('modulo__in', ['chat', 'gerir']), ('nivel', '')), _connector='OR'), name='chk_permissaousuario_nivel')],
            },
        ),
        migrations.CreateModel(
            name='UsuarioPapel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atribuido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atribuicoes_papel_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído por')),
                ('papel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atribuicoes_usuario', to='accounts.papelacesso', verbose_name='Papel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes_papel', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Papel do Usuário',
                'verbose_name_plural': 'Papéis dos Usuários',
                'indexes': [models.Index(fields=['usuario', 'ativo'], name='idx_usuariopapel_usuario_ativo'), models.Index(fields=['papel', 'ativo'], name='idx_usuariopapel_papel_ativo')],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'papel'), name='uniq_usuariopapel_usuario_papel')],
            },
        ),
    ]
