# Generated by Django 5.2.15 on 2026-07-09 00:19

from django.db import migrations


GRUPOS_PADROES = [
    "administrador_escritorio",
    "gerente",
    "advogado",
    "financeiro",
]


def criar_grupos_padroes(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    for nome in GRUPOS_PADROES:
        Group.objects.get_or_create(name=nome)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(criar_grupos_padroes, noop_reverse),
    ]
