# Generated by Django 5.2.15 on 2026-09-23 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_codigo_interno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='habilitacaopapel',
            name='chk_habilitacaopapel_modulo_item',
        ),
        migrations.RemoveConstraint(
            model_name='habilitacaousuario',
            name='chk_habilitacaousuario_modulo_item',
        ),
        migrations.RemoveConstraint(
            model_name='permissaopapel',
            name='chk_permissaopapel_nivel',
        ),
        migrations.RemoveConstraint(
            model_name='permissaousuario',
            name='chk_permissaousuario_nivel',
        ),
        migrations.AlterField(
            model_name='habilitacaopapel',
            name='item',
            field=models.CharField(choices=[('processos_criar', 'Criar processo'), ('processos_editar', 'Editar processo'), ('processos_andamento_adicionar', 'Adicionar andamento'), ('processos_usar_ia', 'Usar assistência de IA'), ('processos_usar_laboratorio', 'Usar Laboratório Jurídico'), ('processos_atribuir_responsavel', 'Atribuir responsabilidade de processos'), ('processos_documento_adicionar', 'Adicionar documento ao processo'), ('processos_documento_excluir', 'Excluir documento do processo'), ('processos_excluir', 'Excluir processo definitivamente'), ('clientes_criar', 'Criar cliente'), ('clientes_editar', 'Editar cliente'), ('clientes_desativar', 'Desativar cliente'), ('clientes_reativar', 'Reativar cliente'), ('clientes_excluir', 'Excluir cliente definitivamente'), ('clientes_documento_adicionar', 'Adicionar documento ao cliente'), ('clientes_documento_excluir', 'Excluir documento do cliente'), ('modelos_criar', 'Criar modelo de peça'), ('modelos_editar_estilo', 'Editar estilo de peças'), ('modelos_editar_alheio', 'Editar modelo de peça de outro usuário'), ('modelos_excluir_alheio', 'Excluir modelo de peça de outro usuário'), ('modelos_gerir_categorias', 'Gerir tipos de peça'), ('agenda_atribuir_outros', 'Atribuir itens da agenda a outros usuários'), ('financeiro_reabrir_lancamento_pago', 'Reabrir lançamento gerado por solicitação paga'), ('gerir_criar_usuario', 'Criar usuário'), ('gerir_habilitar_usuario_processos', 'Habilitar usuário em processos'), ('gerir_criar_equipe', 'Criar equipe'), ('gerir_habilitar_terceiros', 'Habilitar terceiros')], max_length=60, verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='habilitacaopapel',
            name='modulo',
            field=models.CharField(choices=[('processos', 'Processos'), ('clientes', 'Clientes'), ('financeiro', 'Financeiro'), ('modelos', 'Modelos de peças'), ('agenda', 'Agenda Jurídica'), ('gerir', 'Gerir')], max_length=30, verbose_name='Módulo'),
        ),
        migrations.AlterField(
            model_name='habilitacaousuario',
            name='item',
            field=models.CharField(choices=[('processos_criar', 'Criar processo'), ('processos_editar', 'Editar processo'), ('processos_andamento_adicionar', 'Adicionar andamento'), ('processos_usar_ia', 'Usar assistência de IA'), ('processos_usar_laboratorio', 'Usar Laboratório Jurídico'), ('processos_atribuir_responsavel', 'Atribuir responsabilidade de processos'), ('processos_documento_adicionar', 'Adicionar documento ao processo'), ('processos_documento_excluir', 'Excluir documento do processo'), ('processos_excluir', 'Excluir processo definitivamente'), ('clientes_criar', 'Criar cliente'), ('clientes_editar', 'Editar cliente'), ('clientes_desativar', 'Desativar cliente'), ('clientes_reativar', 'Reativar cliente'), ('clientes_excluir', 'Excluir cliente definitivamente'), ('clientes_documento_adicionar', 'Adicionar documento ao cliente'), ('clientes_documento_excluir', 'Excluir documento do cliente'), ('modelos_criar', 'Criar modelo de peça'), ('modelos_editar_estilo', 'Editar estilo de peças'), ('modelos_editar_alheio', 'Editar modelo de peça de outro usuário'), ('modelos_excluir_alheio', 'Excluir modelo de peça de outro usuário'), ('modelos_gerir_categorias', 'Gerir tipos de peça'), ('agenda_atribuir_outros', 'Atribuir itens da agenda a outros usuários'), ('financeiro_reabrir_lancamento_pago', 'Reabrir lançamento gerado por solicitação paga'), ('gerir_criar_usuario', 'Criar usuário'), ('gerir_habilitar_usuario_processos', 'Habilitar usuário em processos'), ('gerir_criar_equipe', 'Criar equipe'), ('gerir_habilitar_terceiros', 'Habilitar terceiros')], max_length=60, verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='habilitacaousuario',
            name='modulo',
            field=models.CharField(choices=[('processos', 'Processos'), ('clientes', 'Clientes'), ('financeiro', 'Financeiro'), ('modelos', 'Modelos de peças'), ('agenda', 'Agenda Jurídica'), ('gerir', 'Gerir')], max_length=30, verbose_name='Módulo'),
        ),
        migrations.AlterField(
            model_name='permissaopapel',
            name='modulo',
            field=models.CharField(choices=[('processos', 'Processos'), ('clientes', 'Clientes'), ('financeiro', 'Financeiro'), ('modelos', 'Modelos de peças'), ('chat', 'Chat'), ('painel', 'Painel'), ('agenda', 'Agenda Jurídica'), ('gerir', 'Gerir')], max_length=30, verbose_name='Módulo'),
        ),
        migrations.AlterField(
            model_name='permissaousuario',
            name='modulo',
            field=models.CharField(choices=[('processos', 'Processos'), ('clientes', 'Clientes'), ('financeiro', 'Financeiro'), ('modelos', 'Modelos de peças'), ('chat', 'Chat'), ('painel', 'Painel'), ('agenda', 'Agenda Jurídica'), ('gerir', 'Gerir')], max_length=30, verbose_name='Módulo'),
        ),
    ]
