# Generated by Django 5.2.15 on 2026-07-19 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_migrar_papeis_legados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HabilitacaoPapel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_conta', models.CharField(choices=[('limitado', 'Limitado'), ('financeiro', 'Financeiro')], max_length=20, verbose_name='Tipo de conta')),
                ('modulo', models.CharField(choices=[('processos', 'Processos'), ('clientes', 'Clientes'), ('tarefas', 'Tarefas'), ('modelos', 'Modelos de peças'), ('agenda', 'Agenda'), ('gerir', 'Gerir')], max_length=30, verbose_name='Módulo')),
                ('item', models.CharField(choices=[('processos_criar', 'Criar processo'), ('processos_editar', 'Editar processo'), ('processos_andamento_adicionar', 'Adicionar andamento'), ('processos_usar_ia', 'Usar assistência de IA'), ('processos_usar_laboratorio', 'Usar Laboratório Jurídico'), ('clientes_criar', 'Criar cliente'), ('clientes_editar', 'Editar cliente'), ('tarefas_atribuir_outros', 'Atribuir tarefa a outros usuários'), ('modelos_criar', 'Criar modelo de peça'), ('modelos_editar_estilo', 'Editar estilo de peças'), ('agenda_criar_para_outros', 'Criar compromisso para outros usuários'), ('gerir_criar_usuario', 'Criar usuário'), ('gerir_habilitar_usuario_processos', 'Habilitar usuário em processos'), ('gerir_criar_equipe', 'Criar equipe'), ('gerir_habilitar_terceiros', 'Habilitar terceiros')], max_length=60, verbose_name='Item')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Habilitação por Tipo de Conta',
                'verbose_name_plural': 'Habilitações por Tipo de Conta',
                'ordering': ['tipo_conta', 'modulo', 'item'],
                'constraints': [models.UniqueConstraint(fields=('tipo_conta', 'modulo', 'item'), name='uniq_habilitacaopapel_tipo_modulo_item'), models.CheckConstraint(condition=models.Q(('tipo_conta__in', ['limitado', 'financeiro'])), name='chk_habilitacaopapel_tipo_conta'), models.CheckConstraint(condition=models.Q(models.Q(('item__in', ['processos_criar', 'processos_editar', 'processos_andamento_adicionar', 'processos_usar_ia', 'processos_usar_laboratorio']), ('modulo', 'processos')), models.Q(('item__in', ['clientes_criar', 'clientes_editar']), ('modulo', 'clientes')), models.Q(('item__in', ['tarefas_atribuir_outros']), ('modulo', 'tarefas')), models.Q(('item__in', ['modelos_criar', 'modelos_editar_estilo']), ('modulo', 'modelos')), models.Q(('item__in', ['agenda_criar_para_outros']), ('modulo', 'agenda')), models.Q(('item__in', ['gerir_criar_usuario', 'gerir_habilitar_usuario_processos', 'gerir_criar_equipe', 'gerir_habilitar_terceiros']), ('modulo', 'gerir')), _connector='OR'), name='chk_habilitacaopapel_modulo_item')],
            },
        ),
        migrations.CreateModel(
            name='PermissaoPapel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_conta', models.CharField(choices=[('limitado', 'Limitado'), ('financeiro', 'Financeiro')], max_length=20, verbose_name='Tipo de conta')),
                ('modulo', models.CharField(choices=[('processos', 'Processos'), ('clientes', 'Clientes'), ('financeiro', 'Financeiro'), ('tarefas', 'Tarefas'), ('modelos', 'Modelos de peças'), ('chat', 'Chat'), ('painel', 'Painel'), ('agenda', 'Agenda'), ('gerir', 'Gerir')], max_length=30, verbose_name='Módulo')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('nivel', models.CharField(blank=True, choices=[('somente_seus', 'Somente os seus'), ('todos', 'Todos'), ('solicitacoes', 'Apenas solicitações'), ('dados', 'Acesso a dados')], default='', help_text='Vazio para módulos sem escopo de dados (chat, gerir).', max_length=30, verbose_name='Nível de acesso')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permissão por Tipo de Conta',
                'verbose_name_plural': 'Permissões por Tipo de Conta',
                'ordering': ['tipo_conta', 'modulo'],
                'constraints': [models.UniqueConstraint(fields=('tipo_conta', 'modulo'), name='uniq_permissaopapel_tipo_modulo'), models.CheckConstraint(condition=models.Q(('tipo_conta__in', ['limitado', 'financeiro'])), name='chk_permissaopapel_tipo_conta'), models.CheckConstraint(condition=models.Q(models.Q(('modulo__in', ['processos', 'clientes', 'tarefas', 'modelos', 'painel', 'agenda']), ('nivel__in', ['somente_seus', 'todos'])), models.Q(('modulo', 'financeiro'), ('nivel__in', ['solicitacoes', 'dados'])), models.Q(('modulo__in', ['chat', 'gerir']), ('nivel', '')), _connector='OR'), name='chk_permissaopapel_nivel')],
            },
        ),
        migrations.CreateModel(
            name='HabilitacaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('processos', 'Processos'), ('clientes', 'Clientes'), ('tarefas', 'Tarefas'), ('modelos', 'Modelos de peças'), ('agenda', 'Agenda'), ('gerir', 'Gerir')], max_length=30, verbose_name='Módulo')),
                ('item', models.CharField(choices=[('processos_criar', 'Criar processo'), ('processos_editar', 'Editar processo'), ('processos_andamento_adicionar', 'Adicionar andamento'), ('processos_usar_ia', 'Usar assistência de IA'), ('processos_usar_laboratorio', 'Usar Laboratório Jurídico'), ('clientes_criar', 'Criar cliente'), ('clientes_editar', 'Editar cliente'), ('tarefas_atribuir_outros', 'Atribuir tarefa a outros usuários'), ('modelos_criar', 'Criar modelo de peça'), ('modelos_editar_estilo', 'Editar estilo de peças'), ('agenda_criar_para_outros', 'Criar compromisso para outros usuários'), ('gerir_criar_usuario', 'Criar usuário'), ('gerir_habilitar_usuario_processos', 'Habilitar usuário em processos'), ('gerir_criar_equipe', 'Criar equipe'), ('gerir_habilitar_terceiros', 'Habilitar terceiros')], max_length=60, verbose_name='Item')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilitacoes_individuais', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Habilitação Individual',
                'verbose_name_plural': 'Habilitações Individuais',
                'ordering': ['usuario', 'modulo', 'item'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'modulo', 'item'), name='uniq_habilitacaousuario_usuario_modulo_item'), models.CheckConstraint(condition=models.Q(models.Q(('item__in', ['processos_criar', 'processos_editar', 'processos_andamento_adicionar', 'processos_usar_ia', 'processos_usar_laboratorio']), ('modulo', 'processos')), models.Q(('item__in', ['clientes_criar', 'clientes_editar']), ('modulo', 'clientes')), models.Q(('item__in', ['tarefas_atribuir_outros']), ('modulo', 'tarefas')), models.Q(('item__in', ['modelos_criar', 'modelos_editar_estilo']), ('modulo', 'modelos')), models.Q(('item__in', ['agenda_criar_para_outros']), ('modulo', 'agenda')), models.Q(('item__in', ['gerir_criar_usuario', 'gerir_habilitar_usuario_processos', 'gerir_criar_equipe', 'gerir_habilitar_terceiros']), ('modulo', 'gerir')), _connector='OR'), name='chk_habilitacaousuario_modulo_item')],
            },
        ),
        migrations.CreateModel(
            name='PermissaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('processos', 'Processos'), ('clientes', 'Clientes'), ('financeiro', 'Financeiro'), ('tarefas', 'Tarefas'), ('modelos', 'Modelos de peças'), ('chat', 'Chat'), ('painel', 'Painel'), ('agenda', 'Agenda'), ('gerir', 'Gerir')], max_length=30, verbose_name='Módulo')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('nivel', models.CharField(blank=True, choices=[('somente_seus', 'Somente os seus'), ('todos', 'Todos'), ('solicitacoes', 'Apenas solicitações'), ('dados', 'Acesso a dados')], default='', help_text='Vazio para módulos sem escopo de dados (chat, gerir).', max_length=30, verbose_name='Nível de acesso')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_individuais', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Permissão Individual',
                'verbose_name_plural': 'Permissões Individuais',
                'ordering': ['usuario', 'modulo'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'modulo'), name='uniq_permissaousuario_usuario_modulo'), models.CheckConstraint(condition=models.Q(models.Q(('modulo__in', ['processos', 'clientes', 'tarefas', 'modelos', 'painel', 'agenda']), ('nivel__in', ['somente_seus', 'todos'])), models.Q(('modulo', 'financeiro'), ('nivel__in', ['solicitacoes', 'dados'])), models.Q(('modulo__in', ['chat', 'gerir']), ('nivel', '')), _connector='OR'), name='chk_permissaousuario_nivel')],
            },
        ),
    ]
