# Generated by Django 5.2.15 on 2026-09-24 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_papel_unico_por_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usuariopapel',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('usuario',), name='uniq_usuariopapel_um_ativo_por_usuario'),
        ),
    ]
