# Generated by Django 5.2.15 on 2026-07-31 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_seed_permissoes_habilitacoes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PapelAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('codigo_preset', models.SlugField(blank=True, help_text='Identificador técnico estável dos presets de fábrica. Nulo para papéis personalizados pelo Tenant Admin.', null=True, verbose_name='Código de preset')),
                ('protegido_sistema', models.BooleanField(default=False, help_text='Presets de fábrica marcados aqui não podem ser excluídos nem ter o codigo_preset alterado pela interface.', verbose_name='Protegido pelo sistema')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Papel de Acesso',
                'verbose_name_plural': 'Papéis de Acesso',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioPapel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Papel do Usuário',
                'verbose_name_plural': 'Papéis dos Usuários',
            },
        ),
        migrations.AddConstraint(
            model_name='perfilusuario',
            constraint=models.UniqueConstraint(condition=models.Q(('is_admin_escritorio', True)), fields=('is_admin_escritorio',), name='uniq_perfil_tenant_admin'),
        ),
        migrations.AddConstraint(
            model_name='papelacesso',
            constraint=models.UniqueConstraint(fields=('nome',), name='uniq_papelacesso_nome'),
        ),
        migrations.AddConstraint(
            model_name='papelacesso',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo_preset__isnull', False)), fields=('codigo_preset',), name='uniq_papelacesso_codigo_preset'),
        ),
        migrations.AddConstraint(
            model_name='papelacesso',
            constraint=models.CheckConstraint(condition=models.Q(('codigo_preset__isnull', True), models.Q(('codigo_preset', ''), _negated=True), _connector='OR'), name='chk_papelacesso_codigo_preset_nao_vazio'),
        ),
        migrations.AddField(
            model_name='habilitacaopapel',
            name='papel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='habilitacoes', to='accounts.papelacesso', verbose_name='Papel (novo sistema)'),
        ),
        migrations.AddField(
            model_name='permissaopapel',
            name='papel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permissoes_modulo', to='accounts.papelacesso', verbose_name='Papel (novo sistema)'),
        ),
        migrations.AddConstraint(
            model_name='habilitacaopapel',
            constraint=models.UniqueConstraint(condition=models.Q(('papel__isnull', False)), fields=('papel', 'modulo', 'item'), name='uniq_habilitacaopapel_papel_modulo_item'),
        ),
        migrations.AddConstraint(
            model_name='permissaopapel',
            constraint=models.UniqueConstraint(condition=models.Q(('papel__isnull', False)), fields=('papel', 'modulo'), name='uniq_permissaopapel_papel_modulo'),
        ),
        migrations.AddField(
            model_name='usuariopapel',
            name='atribuido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atribuicoes_papel_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído por'),
        ),
        migrations.AddField(
            model_name='usuariopapel',
            name='papel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atribuicoes_usuario', to='accounts.papelacesso', verbose_name='Papel'),
        ),
        migrations.AddField(
            model_name='usuariopapel',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes_papel', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddIndex(
            model_name='usuariopapel',
            index=models.Index(fields=['usuario', 'ativo'], name='idx_usuariopapel_usuario_ativo'),
        ),
        migrations.AddIndex(
            model_name='usuariopapel',
            index=models.Index(fields=['papel', 'ativo'], name='idx_usuariopapel_papel_ativo'),
        ),
        migrations.AddConstraint(
            model_name='usuariopapel',
            constraint=models.UniqueConstraint(fields=('usuario', 'papel'), name='uniq_usuariopapel_usuario_papel'),
        ),
    ]
