# Generated by Django 5.2.15 on 2026-09-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_um_papel_ativo_por_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='oab_numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número da OAB'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='oab_uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF da OAB'),
        ),
    ]
