# Generated by Django 5.2.15 on 2026-07-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_adicionar_papeis_dinamicos'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='habilitacaopapel',
            name='uniq_habilitacaopapel_tipo_modulo_item',
        ),
        migrations.RemoveConstraint(
            model_name='habilitacaopapel',
            name='chk_habilitacaopapel_tipo_conta',
        ),
        migrations.RemoveConstraint(
            model_name='permissaopapel',
            name='uniq_permissaopapel_tipo_modulo',
        ),
        migrations.RemoveConstraint(
            model_name='permissaopapel',
            name='chk_permissaopapel_tipo_conta',
        ),
        migrations.AlterField(
            model_name='habilitacaopapel',
            name='tipo_conta',
            field=models.CharField(blank=True, choices=[('limitado', 'Limitado'), ('financeiro', 'Financeiro')], max_length=20, null=True, verbose_name='Tipo de conta'),
        ),
        migrations.AlterField(
            model_name='permissaopapel',
            name='tipo_conta',
            field=models.CharField(blank=True, choices=[('limitado', 'Limitado'), ('financeiro', 'Financeiro')], max_length=20, null=True, verbose_name='Tipo de conta'),
        ),
        migrations.AddConstraint(
            model_name='habilitacaopapel',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo_conta__isnull', False)), fields=('tipo_conta', 'modulo', 'item'), name='uniq_habilitacaopapel_tipo_modulo_item_legado'),
        ),
        migrations.AddConstraint(
            model_name='habilitacaopapel',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_conta__isnull', True), ('tipo_conta__in', ['limitado', 'financeiro']), _connector='OR'), name='chk_habilitacaopapel_tipo_conta_legado_ou_nulo'),
        ),
        migrations.AddConstraint(
            model_name='permissaopapel',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo_conta__isnull', False)), fields=('tipo_conta', 'modulo'), name='uniq_permissaopapel_tipo_modulo_legado'),
        ),
        migrations.AddConstraint(
            model_name='permissaopapel',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_conta__isnull', True), ('tipo_conta__in', ['limitado', 'financeiro']), _connector='OR'), name='chk_permissaopapel_tipo_conta_legado_ou_nulo'),
        ),
    ]
