# Generated by Django 5.2.15 on 2026-08-01 02:11
# Editado manualmente: RunPython inserido antes das AddConstraint.
#
# Rollback de produção: RunPython.noop — não remove dados criados.
# Para reverter em produção, utilizar backup ou migration corretiva futura.

from django.conf import settings
from django.db import migrations


def migrar_papeis_e_presets(apps, schema_editor):
    """
    Cria cinco PapelAcesso de fábrica, associa registros legados de
    PermissaoPapel e HabilitacaoPapel aos papéis convertidos, vincula
    usuários dos grupos legados via UsuarioPapel, e insere as matrizes
    de permissões e habilitações para os três novos presets.

    Slugs de módulos e itens são duplicados literalmente aqui para
    preservar o comportamento histórico independentemente de alterações
    futuras em permissoes_constants.py.
    """

    PapelAcesso = apps.get_model("accounts", "PapelAcesso")
    PermissaoPapel = apps.get_model("accounts", "PermissaoPapel")
    HabilitacaoPapel = apps.get_model("accounts", "HabilitacaoPapel")
    UsuarioPapel = apps.get_model("accounts", "UsuarioPapel")
    PerfilUsuario = apps.get_model("accounts", "PerfilUsuario")
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Group = apps.get_model("auth", "Group")

    # ── Catálogo estático (duplicado de permissoes_constants.py) ─────────────
    MODULO_CHOICES_SLUGS = [
        'processos', 'clientes', 'financeiro', 'tarefas', 'modelos',
        'chat', 'painel', 'agenda', 'gerir',
    ]
    NIVEIS_POR_MODULO = {
        'processos':  ['somente_seus', 'todos'],
        'clientes':   ['somente_seus', 'todos'],
        'tarefas':    ['somente_seus', 'todos'],
        'modelos':    ['somente_seus', 'todos'],
        'painel':     ['somente_seus', 'todos'],
        'agenda':     ['somente_seus', 'todos'],
        'financeiro': ['solicitacoes', 'dados'],
        'chat':       [''],
        'gerir':      [''],
    }
    ITENS_POR_MODULO = {
        'processos': [
            'processos_criar',
            'processos_editar',
            'processos_andamento_adicionar',
            'processos_usar_ia',
            'processos_usar_laboratorio',
        ],
        'clientes': ['clientes_criar', 'clientes_editar'],
        'tarefas':  ['tarefas_atribuir_outros'],
        'modelos':  ['modelos_criar', 'modelos_editar_estilo'],
        'agenda':   ['agenda_criar_para_outros'],
        'gerir': [
            'gerir_criar_usuario',
            'gerir_habilitar_usuario_processos',
            'gerir_criar_equipe',
            'gerir_habilitar_terceiros',
        ],
    }

    # ── Definições dos cinco presets de fábrica ───────────────────────────────
    PRESETS = [
        {
            'codigo_preset': 'socio_gestor_nucleo',
            'nome': 'Sócio / Gestor de Núcleo',
            'descricao': (
                'Gestão operacional de núcleo. Os escopos de equipe e a visão financeira '
                'do núcleo serão configurados nas etapas específicas de delegação e financeiro.'
            ),
        },
        {
            'codigo_preset': 'advogado_associado',
            'nome': 'Advogado Associado',
            'descricao': (
                'Atuação nos processos, clientes, tarefas, modelos e compromissos '
                'vinculados ao usuário.'
            ),
        },
        {
            'codigo_preset': 'estagiario_paralegal',
            'nome': 'Estagiário / Paralegal',
            'descricao': (
                'Acesso operacional restrito aos processos, tarefas e compromissos vinculados.'
            ),
        },
        {
            'codigo_preset': 'gestor_financeiro',
            'nome': 'Gestor Financeiro',
            'descricao': (
                'Gestão financeira do escritório e consulta operacional de clientes, '
                'tarefas, agenda e painel.'
            ),
        },
        {
            'codigo_preset': 'secretaria_recepcao',
            'nome': 'Secretaria / Recepção',
            'descricao': (
                'Atendimento, cadastro de clientes, organização da agenda e apoio administrativo.'
            ),
        },
    ]

    # ── Criar presets (get_or_create por codigo_preset) ──────────────────────
    papeis = {}
    for p in PRESETS:
        # Guardia: não apropriar papel customizado com mesmo nome mas código diferente
        conflito = (
            PapelAcesso.objects
            .filter(nome=p['nome'])
            .exclude(codigo_preset=p['codigo_preset'])
            .first()
        )
        if conflito:
            raise RuntimeError(
                f"Conflito de nome: PapelAcesso '{p['nome']}' já existe com "
                f"codigo_preset='{conflito.codigo_preset}' (esperado '{p['codigo_preset']}'). "
                f"Revisão manual necessária antes de aplicar esta migration."
            )
        papel, _ = PapelAcesso.objects.get_or_create(
            codigo_preset=p['codigo_preset'],
            defaults={
                'nome': p['nome'],
                'descricao': p['descricao'],
                'ativo': True,
                'protegido_sistema': True,
            },
        )
        papeis[p['codigo_preset']] = papel

    papel_adv_assoc = papeis['advogado_associado']
    papel_gest_fin = papeis['gestor_financeiro']

    # ── Detectar ambiguidades nos grupos técnicos ────────────────────────────
    try:
        grupo_limitado = Group.objects.get(name='limitado')
        pks_limitado = set(grupo_limitado.user_set.values_list('pk', flat=True))
    except Group.DoesNotExist:
        pks_limitado = set()

    try:
        grupo_financeiro = Group.objects.get(name='financeiro')
        pks_financeiro = set(grupo_financeiro.user_set.values_list('pk', flat=True))
    except Group.DoesNotExist:
        pks_financeiro = set()

    simultaneos = pks_limitado & pks_financeiro
    if simultaneos:
        usernames = list(
            User.objects.filter(pk__in=simultaneos).values_list('username', flat=True)
        )
        raise RuntimeError(
            f"Usuários simultaneamente em 'limitado' e 'financeiro': {usernames}. "
            f"Não é possível migrar automaticamente sem elevar acesso inesperadamente. "
            f"Resolva o conflito manualmente antes de aplicar esta migration."
        )

    # Verificar grupos legados sem tipo técnico definido
    for nome_grupo in ('gerente', 'advogado'):
        try:
            g = Group.objects.get(name=nome_grupo)
            pks_leg = set(g.user_set.values_list('pk', flat=True))
            sem_tecnico = pks_leg - pks_limitado - pks_financeiro
            if sem_tecnico:
                usernames = list(
                    User.objects.filter(pk__in=sem_tecnico).values_list('username', flat=True)
                )
                raise RuntimeError(
                    f"Usuários no grupo '{nome_grupo}' sem tipo técnico definido "
                    f"(nem limitado nem financeiro): {usernames}. "
                    f"Revisão manual necessária antes de aplicar esta migration."
                )
        except Group.DoesNotExist:
            pass

    # ── Migrar PermissaoPapel legadas para papéis dinâmicos ──────────────────
    for tipo_conta, papel_alvo in [
        ('limitado', papel_adv_assoc),
        ('financeiro', papel_gest_fin),
    ]:
        # Guardia: não sobrescrever associação a outro papel
        conflito = (
            PermissaoPapel.objects
            .filter(tipo_conta=tipo_conta)
            .exclude(papel__isnull=True)
            .exclude(papel=papel_alvo)
            .first()
        )
        if conflito:
            raise RuntimeError(
                f"PermissaoPapel com tipo_conta='{tipo_conta}' já está associada a "
                f"'{conflito.papel}' (esperado '{papel_alvo.nome}'). Revisão manual necessária."
            )
        PermissaoPapel.objects.filter(
            tipo_conta=tipo_conta, papel__isnull=True
        ).update(papel=papel_alvo)

    # ── Migrar HabilitacaoPapel legadas para papéis dinâmicos ────────────────
    for tipo_conta, papel_alvo in [
        ('limitado', papel_adv_assoc),
        ('financeiro', papel_gest_fin),
    ]:
        conflito = (
            HabilitacaoPapel.objects
            .filter(tipo_conta=tipo_conta)
            .exclude(papel__isnull=True)
            .exclude(papel=papel_alvo)
            .first()
        )
        if conflito:
            raise RuntimeError(
                f"HabilitacaoPapel com tipo_conta='{tipo_conta}' já está associada a "
                f"'{conflito.papel}' (esperado '{papel_alvo.nome}'). Revisão manual necessária."
            )
        HabilitacaoPapel.objects.filter(
            tipo_conta=tipo_conta, papel__isnull=True
        ).update(papel=papel_alvo)

    # ── Criar UsuarioPapel para grupos legados ────────────────────────────────
    pks_admin = set(
        PerfilUsuario.objects.filter(is_admin_escritorio=True).values_list('user_id', flat=True)
    )

    for user_pk in pks_limitado - pks_admin:
        UsuarioPapel.objects.get_or_create(
            usuario_id=user_pk,
            papel=papel_adv_assoc,
            defaults={'ativo': True, 'atribuido_por_id': None},
        )

    for user_pk in pks_financeiro - pks_admin:
        UsuarioPapel.objects.get_or_create(
            usuario_id=user_pk,
            papel=papel_gest_fin,
            defaults={'ativo': True, 'atribuido_por_id': None},
        )

    # ── Matrizes dos três novos presets ───────────────────────────────────────
    # Formato: (modulo, ativo, nivel)
    MATRIZES_PERMISSOES = {
        'socio_gestor_nucleo': [
            ('processos',  True,  'somente_seus'),
            ('clientes',   True,  'somente_seus'),
            ('financeiro', False, 'solicitacoes'),
            ('tarefas',    True,  'somente_seus'),
            ('modelos',    True,  'somente_seus'),
            ('chat',       True,  ''),
            ('painel',     True,  'somente_seus'),
            ('agenda',     True,  'somente_seus'),
            ('gerir',      False, ''),
        ],
        'estagiario_paralegal': [
            ('processos',  True,  'somente_seus'),
            ('clientes',   True,  'somente_seus'),
            ('financeiro', False, 'solicitacoes'),
            ('tarefas',    True,  'somente_seus'),
            ('modelos',    True,  'somente_seus'),
            ('chat',       True,  ''),
            ('painel',     True,  'somente_seus'),
            ('agenda',     True,  'somente_seus'),
            ('gerir',      False, ''),
        ],
        'secretaria_recepcao': [
            ('processos',  False, 'somente_seus'),
            ('clientes',   True,  'todos'),
            ('financeiro', False, 'solicitacoes'),
            ('tarefas',    True,  'somente_seus'),
            ('modelos',    False, 'somente_seus'),
            ('chat',       True,  ''),
            ('painel',     True,  'somente_seus'),
            ('agenda',     True,  'todos'),
            ('gerir',      False, ''),
        ],
    }

    # Formato: (modulo, item, ativo)
    MATRIZES_HABILITACOES = {
        'socio_gestor_nucleo': [
            ('processos', 'processos_andamento_adicionar', True),
            ('processos', 'processos_criar',               True),
            ('processos', 'processos_editar',              True),
            ('processos', 'processos_usar_ia',             True),
            ('processos', 'processos_usar_laboratorio',    True),
            ('clientes',  'clientes_criar',                True),
            ('clientes',  'clientes_editar',               True),
            ('tarefas',   'tarefas_atribuir_outros',       True),
            ('modelos',   'modelos_criar',                 True),
            ('modelos',   'modelos_editar_estilo',         True),
            ('agenda',    'agenda_criar_para_outros',      True),
            ('gerir',     'gerir_criar_equipe',            False),
            ('gerir',     'gerir_criar_usuario',           False),
            ('gerir',     'gerir_habilitar_terceiros',     False),
            ('gerir',     'gerir_habilitar_usuario_processos', False),
        ],
        'estagiario_paralegal': [
            ('processos', 'processos_andamento_adicionar', True),
            ('processos', 'processos_criar',               False),
            ('processos', 'processos_editar',              True),
            ('processos', 'processos_usar_ia',             False),
            ('processos', 'processos_usar_laboratorio',    False),
            ('clientes',  'clientes_criar',                False),
            ('clientes',  'clientes_editar',               False),
            ('tarefas',   'tarefas_atribuir_outros',       False),
            ('modelos',   'modelos_criar',                 False),
            ('modelos',   'modelos_editar_estilo',         False),
            ('agenda',    'agenda_criar_para_outros',      False),
            ('gerir',     'gerir_criar_equipe',            False),
            ('gerir',     'gerir_criar_usuario',           False),
            ('gerir',     'gerir_habilitar_terceiros',     False),
            ('gerir',     'gerir_habilitar_usuario_processos', False),
        ],
        'secretaria_recepcao': [
            ('processos', 'processos_andamento_adicionar', False),
            ('processos', 'processos_criar',               False),
            ('processos', 'processos_editar',              False),
            ('processos', 'processos_usar_ia',             False),
            ('processos', 'processos_usar_laboratorio',    False),
            ('clientes',  'clientes_criar',                True),
            ('clientes',  'clientes_editar',               True),
            ('tarefas',   'tarefas_atribuir_outros',       False),
            ('modelos',   'modelos_criar',                 False),
            ('modelos',   'modelos_editar_estilo',         False),
            ('agenda',    'agenda_criar_para_outros',      True),
            ('gerir',     'gerir_criar_equipe',            False),
            ('gerir',     'gerir_criar_usuario',           False),
            ('gerir',     'gerir_habilitar_terceiros',     False),
            ('gerir',     'gerir_habilitar_usuario_processos', False),
        ],
    }

    for codigo_preset, linhas in MATRIZES_PERMISSOES.items():
        papel = papeis[codigo_preset]
        for modulo, ativo, nivel in linhas:
            # Validação do catálogo embutido
            if modulo not in MODULO_CHOICES_SLUGS:
                raise RuntimeError(
                    f"Módulo inválido na matriz de '{codigo_preset}': '{modulo}'. "
                    f"O catálogo embutido diverge de permissoes_constants.py."
                )
            niveis_validos = NIVEIS_POR_MODULO.get(modulo, [])
            if nivel not in niveis_validos:
                raise RuntimeError(
                    f"Nível '{nivel}' inválido para módulo '{modulo}' no preset '{codigo_preset}'. "
                    f"Válidos: {niveis_validos}."
                )
            PermissaoPapel.objects.get_or_create(
                papel=papel,
                modulo=modulo,
                defaults={'tipo_conta': None, 'ativo': ativo, 'nivel': nivel},
            )

    for codigo_preset, linhas in MATRIZES_HABILITACOES.items():
        papel = papeis[codigo_preset]
        for modulo, item, ativo in linhas:
            # Validação do catálogo embutido
            itens_validos = ITENS_POR_MODULO.get(modulo, [])
            if item not in itens_validos:
                raise RuntimeError(
                    f"Item '{item}' inválido para módulo '{modulo}' no preset '{codigo_preset}'. "
                    f"Válidos: {itens_validos}."
                )
            HabilitacaoPapel.objects.get_or_create(
                papel=papel,
                modulo=modulo,
                item=item,
                defaults={'tipo_conta': None, 'ativo': ativo},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_preparar_transicao_papeis_dinamicos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            migrar_papeis_e_presets,
            migrations.RunPython.noop,
        ),
    ]
