# Generated by Django 5.2.15 on 2026-08-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_migrar_papeis_e_presets'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='habilitacaopapel',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_conta__isnull', False), ('papel__isnull', False), _connector='OR'), name='chk_habilitacaopapel_tipo_ou_papel'),
        ),
        migrations.AddConstraint(
            model_name='permissaopapel',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_conta__isnull', False), ('papel__isnull', False), _connector='OR'), name='chk_permissaopapel_tipo_ou_papel'),
        ),
    ]
