# Generated by Django 5.2.15 on 2026-09-03 13:11

import apps.saas_tenants.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_seed_habilitacao_reabrir_lancamento_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.saas_tenants.storage.CaminhoArquivoTenant('protegido', 'accounts/avatares')),
        ),
    ]
