# Generated by Django 5.2.15 on 2026-09-04 14:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remover_nivel_dados_legado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='habilitacaopapel',
            name='chk_habilitacaopapel_modulo_item',
        ),
        migrations.RemoveConstraint(
            model_name='habilitacaousuario',
            name='chk_habilitacaousuario_modulo_item',
        ),
        migrations.AlterField(
            model_name='habilitacaopapel',
            name='item',
            field=models.CharField(choices=[('processos_criar', 'Criar processo'), ('processos_editar', 'Editar processo'), ('processos_andamento_adicionar', 'Adicionar andamento'), ('processos_usar_ia', 'Usar assistência de IA'), ('processos_usar_laboratorio', 'Usar Laboratório Jurídico'), ('processos_atribuir_responsavel', 'Atribuir responsabilidade de processos'), ('clientes_criar', 'Criar cliente'), ('clientes_editar', 'Editar cliente'), ('clientes_desativar', 'Desativar cliente'), ('clientes_reativar', 'Reativar cliente'), ('tarefas_atribuir_outros', 'Atribuir tarefa a outros usuários'), ('modelos_criar', 'Criar modelo de peça'), ('modelos_editar_estilo', 'Editar estilo de peças'), ('agenda_criar_para_outros', 'Criar compromisso para outros usuários'), ('financeiro_reabrir_lancamento_pago', 'Reabrir lançamento gerado por solicitação paga'), ('gerir_criar_usuario', 'Criar usuário'), ('gerir_habilitar_usuario_processos', 'Habilitar usuário em processos'), ('gerir_criar_equipe', 'Criar equipe'), ('gerir_habilitar_terceiros', 'Habilitar terceiros')], max_length=60, verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='habilitacaousuario',
            name='item',
            field=models.CharField(choices=[('processos_criar', 'Criar processo'), ('processos_editar', 'Editar processo'), ('processos_andamento_adicionar', 'Adicionar andamento'), ('processos_usar_ia', 'Usar assistência de IA'), ('processos_usar_laboratorio', 'Usar Laboratório Jurídico'), ('processos_atribuir_responsavel', 'Atribuir responsabilidade de processos'), ('clientes_criar', 'Criar cliente'), ('clientes_editar', 'Editar cliente'), ('clientes_desativar', 'Desativar cliente'), ('clientes_reativar', 'Reativar cliente'), ('tarefas_atribuir_outros', 'Atribuir tarefa a outros usuários'), ('modelos_criar', 'Criar modelo de peça'), ('modelos_editar_estilo', 'Editar estilo de peças'), ('agenda_criar_para_outros', 'Criar compromisso para outros usuários'), ('financeiro_reabrir_lancamento_pago', 'Reabrir lançamento gerado por solicitação paga'), ('gerir_criar_usuario', 'Criar usuário'), ('gerir_habilitar_usuario_processos', 'Habilitar usuário em processos'), ('gerir_criar_equipe', 'Criar equipe'), ('gerir_habilitar_terceiros', 'Habilitar terceiros')], max_length=60, verbose_name='Item'),
        ),
        migrations.AddConstraint(
            model_name='habilitacaopapel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('item__in', ['processos_criar', 'processos_editar', 'processos_andamento_adicionar', 'processos_usar_ia', 'processos_usar_laboratorio', 'processos_atribuir_responsavel']), ('modulo', 'processos')), models.Q(('item__in', ['clientes_criar', 'clientes_editar', 'clientes_desativar', 'clientes_reativar']), ('modulo', 'clientes')), models.Q(('item__in', ['tarefas_atribuir_outros']), ('modulo', 'tarefas')), models.Q(('item__in', ['modelos_criar', 'modelos_editar_estilo']), ('modulo', 'modelos')), models.Q(('item__in', ['agenda_criar_para_outros']), ('modulo', 'agenda')), models.Q(('item__in', ['financeiro_reabrir_lancamento_pago']), ('modulo', 'financeiro')), models.Q(('item__in', ['gerir_criar_usuario', 'gerir_habilitar_usuario_processos', 'gerir_criar_equipe', 'gerir_habilitar_terceiros']), ('modulo', 'gerir')), _connector='OR'), name='chk_habilitacaopapel_modulo_item'),
        ),
        migrations.AddConstraint(
            model_name='habilitacaousuario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('item__in', ['processos_criar', 'processos_editar', 'processos_andamento_adicionar', 'processos_usar_ia', 'processos_usar_laboratorio', 'processos_atribuir_responsavel']), ('modulo', 'processos')), models.Q(('item__in', ['clientes_criar', 'clientes_editar', 'clientes_desativar', 'clientes_reativar']), ('modulo', 'clientes')), models.Q(('item__in', ['tarefas_atribuir_outros']), ('modulo', 'tarefas')), models.Q(('item__in', ['modelos_criar', 'modelos_editar_estilo']), ('modulo', 'modelos')), models.Q(('item__in', ['agenda_criar_para_outros']), ('modulo', 'agenda')), models.Q(('item__in', ['financeiro_reabrir_lancamento_pago']), ('modulo', 'financeiro')), models.Q(('item__in', ['gerir_criar_usuario', 'gerir_habilitar_usuario_processos', 'gerir_criar_equipe', 'gerir_habilitar_terceiros']), ('modulo', 'gerir')), _connector='OR'), name='chk_habilitacaousuario_modulo_item'),
        ),
    ]
