# Generated by Django 5.2.15 on 2026-09-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_adicionar_habilitacoes_documento_processos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilitacaopapel',
            name='item',
            field=models.CharField(choices=[('processos_criar', 'Criar processo'), ('processos_editar', 'Editar processo'), ('processos_andamento_adicionar', 'Adicionar andamento'), ('processos_usar_ia', 'Usar assistência de IA'), ('processos_usar_laboratorio', 'Usar Laboratório Jurídico'), ('processos_atribuir_responsavel', 'Atribuir responsabilidade de processos'), ('processos_documento_adicionar', 'Adicionar documento ao processo'), ('processos_documento_excluir', 'Excluir documento do processo'), ('processos_excluir', 'Excluir processo definitivamente'), ('clientes_criar', 'Criar cliente'), ('clientes_editar', 'Editar cliente'), ('clientes_desativar', 'Desativar cliente'), ('clientes_reativar', 'Reativar cliente'), ('tarefas_atribuir_outros', 'Atribuir tarefa a outros usuários'), ('modelos_criar', 'Criar modelo de peça'), ('modelos_editar_estilo', 'Editar estilo de peças'), ('modelos_editar_alheio', 'Editar modelo de peça de outro usuário'), ('modelos_excluir_alheio', 'Excluir modelo de peça de outro usuário'), ('modelos_gerir_categorias', 'Gerir categorias de modelo de peça'), ('agenda_criar_para_outros', 'Criar compromisso para outros usuários'), ('financeiro_reabrir_lancamento_pago', 'Reabrir lançamento gerado por solicitação paga'), ('gerir_criar_usuario', 'Criar usuário'), ('gerir_habilitar_usuario_processos', 'Habilitar usuário em processos'), ('gerir_criar_equipe', 'Criar equipe'), ('gerir_habilitar_terceiros', 'Habilitar terceiros')], max_length=60, verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='habilitacaousuario',
            name='item',
            field=models.CharField(choices=[('processos_criar', 'Criar processo'), ('processos_editar', 'Editar processo'), ('processos_andamento_adicionar', 'Adicionar andamento'), ('processos_usar_ia', 'Usar assistência de IA'), ('processos_usar_laboratorio', 'Usar Laboratório Jurídico'), ('processos_atribuir_responsavel', 'Atribuir responsabilidade de processos'), ('processos_documento_adicionar', 'Adicionar documento ao processo'), ('processos_documento_excluir', 'Excluir documento do processo'), ('processos_excluir', 'Excluir processo definitivamente'), ('clientes_criar', 'Criar cliente'), ('clientes_editar', 'Editar cliente'), ('clientes_desativar', 'Desativar cliente'), ('clientes_reativar', 'Reativar cliente'), ('tarefas_atribuir_outros', 'Atribuir tarefa a outros usuários'), ('modelos_criar', 'Criar modelo de peça'), ('modelos_editar_estilo', 'Editar estilo de peças'), ('modelos_editar_alheio', 'Editar modelo de peça de outro usuário'), ('modelos_excluir_alheio', 'Excluir modelo de peça de outro usuário'), ('modelos_gerir_categorias', 'Gerir categorias de modelo de peça'), ('agenda_criar_para_outros', 'Criar compromisso para outros usuários'), ('financeiro_reabrir_lancamento_pago', 'Reabrir lançamento gerado por solicitação paga'), ('gerir_criar_usuario', 'Criar usuário'), ('gerir_habilitar_usuario_processos', 'Habilitar usuário em processos'), ('gerir_criar_equipe', 'Criar equipe'), ('gerir_habilitar_terceiros', 'Habilitar terceiros')], max_length=60, verbose_name='Item'),
        ),
    ]
