# Generated by Django 5.2.15 on 2026-09-14 16:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_habilitacaopapel_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='habilitacaopapel',
            name='chk_habilitacaopapel_modulo_item',
        ),
        migrations.RemoveConstraint(
            model_name='habilitacaousuario',
            name='chk_habilitacaousuario_modulo_item',
        ),
        migrations.AddConstraint(
            model_name='habilitacaopapel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('item__in', ['processos_criar', 'processos_editar', 'processos_andamento_adicionar', 'processos_usar_ia', 'processos_usar_laboratorio', 'processos_atribuir_responsavel', 'processos_documento_adicionar', 'processos_documento_excluir', 'processos_excluir']), ('modulo', 'processos')), models.Q(('item__in', ['clientes_criar', 'clientes_editar', 'clientes_desativar', 'clientes_reativar']), ('modulo', 'clientes')), models.Q(('item__in', ['tarefas_atribuir_outros']), ('modulo', 'tarefas')), models.Q(('item__in', ['modelos_criar', 'modelos_editar_estilo', 'modelos_editar_alheio', 'modelos_excluir_alheio', 'modelos_gerir_categorias']), ('modulo', 'modelos')), models.Q(('item__in', ['agenda_criar_para_outros']), ('modulo', 'agenda')), models.Q(('item__in', ['financeiro_reabrir_lancamento_pago']), ('modulo', 'financeiro')), models.Q(('item__in', ['gerir_criar_usuario', 'gerir_habilitar_usuario_processos', 'gerir_criar_equipe', 'gerir_habilitar_terceiros']), ('modulo', 'gerir')), _connector='OR'), name='chk_habilitacaopapel_modulo_item'),
        ),
        migrations.AddConstraint(
            model_name='habilitacaousuario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('item__in', ['processos_criar', 'processos_editar', 'processos_andamento_adicionar', 'processos_usar_ia', 'processos_usar_laboratorio', 'processos_atribuir_responsavel', 'processos_documento_adicionar', 'processos_documento_excluir', 'processos_excluir']), ('modulo', 'processos')), models.Q(('item__in', ['clientes_criar', 'clientes_editar', 'clientes_desativar', 'clientes_reativar']), ('modulo', 'clientes')), models.Q(('item__in', ['tarefas_atribuir_outros']), ('modulo', 'tarefas')), models.Q(('item__in', ['modelos_criar', 'modelos_editar_estilo', 'modelos_editar_alheio', 'modelos_excluir_alheio', 'modelos_gerir_categorias']), ('modulo', 'modelos')), models.Q(('item__in', ['agenda_criar_para_outros']), ('modulo', 'agenda')), models.Q(('item__in', ['financeiro_reabrir_lancamento_pago']), ('modulo', 'financeiro')), models.Q(('item__in', ['gerir_criar_usuario', 'gerir_habilitar_usuario_processos', 'gerir_criar_equipe', 'gerir_habilitar_terceiros']), ('modulo', 'gerir')), _connector='OR'), name='chk_habilitacaousuario_modulo_item'),
        ),
    ]
