# Generated by Django 5.2.15 on 2026-09-17 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_remove_habilitacaopapel_chk_habilitacaopapel_modulo_item_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipeVinculada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='accounts.equipe')),
            ],
            options={
                'verbose_name': 'Equipe Vinculada',
                'verbose_name_plural': 'Equipes Vinculadas',
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'equipe'), name='uniq_equipe_vinculada')],
            },
        ),
        migrations.CreateModel(
            name='VinculoIntegrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_integrante', to='accounts.equipe')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_integrante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vínculo de Integrante',
                'verbose_name_plural': 'Vínculos de Integrante',
                'constraints': [models.UniqueConstraint(condition=models.Q(('equipe__isnull', False)), fields=('content_type', 'object_id', 'usuario', 'equipe'), name='uniq_vinculo_integrante_via_equipe'), models.UniqueConstraint(condition=models.Q(('equipe__isnull', True)), fields=('content_type', 'object_id', 'usuario'), name='uniq_vinculo_integrante_individual')],
            },
        ),
    ]
