# Generated by Django 5.2.15 on 2026-09-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_equipevinculada_vinculointegrante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='equipe_pai',
        ),
    ]
