# Generated by Django 5.2.15 on 2026-09-22 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_remove_tipo_conta_papel_obrigatorio'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConviteDelegacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito'), ('recusado', 'Recusado')], default='pendente', max_length=10)),
                ('justificativa_recusa', models.TextField(blank=True)),
                ('object_id', models.PositiveIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('respondido_em', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('delegante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convites_delegacao_enviados', to=settings.AUTH_USER_MODEL)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_delegacao_recebidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Convite de delegação',
                'verbose_name_plural': 'Convites de delegação',
                'ordering': ['-criado_em'],
            },
        ),
    ]
