# Generated by Django 5.2.15 on 2026-07-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEscritorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_escritorio', models.CharField(blank=True, max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('endereco', models.TextField(blank=True)),
                ('site', models.URLField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Escritório',
                'verbose_name_plural': 'Configurações do Escritório',
            },
        ),
    ]
