# Generated by Django 5.2.15 on 2026-09-13 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processos', '0014_processo_cidade_processo_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('login', 'Login no sistema'), ('processo_criado', 'Criou processo'), ('processo_editado', 'Editou processo'), ('processo_arquivado', 'Arquivou processo'), ('processo_reaberto', 'Reabriu processo'), ('processo_andamento_adicionado', 'Adicionou andamento'), ('processo_parte_adicionada', 'Adicionou parte'), ('processo_parte_editada', 'Editou parte'), ('processo_apenso_adicionado', 'Adicionou apenso'), ('processo_apenso_removido', 'Removeu apenso'), ('processo_integrante_adicionado', 'Adicionou integrante habilitado'), ('processo_integrante_removido', 'Removeu integrante habilitado'), ('processo_documento_adicionado', 'Adicionou documento'), ('processo_documento_excluido', 'Excluiu documento')], max_length=40)),
                ('descricao', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_atividade', to='processos.processo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_atividade', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de atividade',
                'verbose_name_plural': 'Logs de atividade',
                'ordering': ['-criado_em'],
            },
        ),
    ]
