# Generated by Django 5.2.15 on 2026-06-08 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CasoLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_peca', models.CharField(choices=[('peticao_inicial', 'Petição inicial'), ('contestacao', 'Contestação'), ('recurso', 'Recurso'), ('contrato', 'Contrato'), ('notificacao', 'Notificação extrajudicial'), ('outro', 'Outro')], max_length=30)),
                ('area_direito', models.CharField(max_length=50)),
                ('tipo_cliente', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2)),
                ('nome_cliente', models.CharField(max_length=255)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=18)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('processando', 'Processando'), ('concluido', 'Concluído')], default='rascunho', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caso – Laboratório',
                'verbose_name_plural': 'Casos – Laboratório',
                'ordering': ['-criado_em'],
            },
        ),
    ]
