# Generated by Django 5.2.15 on 2026-09-03 12:42

import apps.saas_tenants.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaovisual',
            name='favicon',
            field=models.ImageField(blank=True, null=True, storage=apps.saas_tenants.storage.StorageIdentidadeVisual('favicon'), upload_to=apps.saas_tenants.storage.CaminhoArquivoTenant('publico', 'identidade-visual/favicons')),
        ),
        migrations.AlterField(
            model_name='configuracaovisual',
            name='imagem_fundo_login',
            field=models.ImageField(blank=True, null=True, storage=apps.saas_tenants.storage.StorageIdentidadeVisual('fundo-login'), upload_to=apps.saas_tenants.storage.CaminhoArquivoTenant('publico', 'identidade-visual/fundos-login')),
        ),
        migrations.AlterField(
            model_name='configuracaovisual',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=apps.saas_tenants.storage.StorageIdentidadeVisual('logo'), upload_to=apps.saas_tenants.storage.CaminhoArquivoTenant('publico', 'identidade-visual/logos')),
        ),
    ]
