# Generated by Django 5.2.15 on 2026-09-22 19:23

import apps.saas_tenants.storage
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('numero', models.CharField(blank=True, max_length=50)),
                ('area_direito', models.CharField(choices=[('CÍVEL', 'Civil'), ('CONSUMIDOR', 'Consumidor'), ('TRABALHISTA', 'Trabalhista'), ('SUCESSÕES', 'Sucessões'), ('CRIMINAL', 'Penal'), ('ADMINISTRATIVO', 'Administrativo'), ('TRIBUTÁRIO', 'Tributário'), ('FAMÍLIA', 'Família'), ('EMPRESARIAL', 'Empresarial'), ('MÉDICO', 'Médico'), ('PREVIDENCIÁRIO', 'Previdenciário'), ('DIGITAL', 'Digital'), ('PROPRIEDADE_INTELECTUAL', 'Propriedade Intelectual'), ('IMOBILIÁRIO', 'Imobiliário'), ('DESPORTIVO', 'Desportivo'), ('DIREITO_INTERNACIONAL', 'Direito Internacional'), ('OUTRO', 'Outro')], default='CÍVEL', max_length=30)),
                ('instancia', models.CharField(blank=True, default='1ª Instância', max_length=50)),
                ('vara', models.CharField(blank=True, max_length=255)),
                ('comarca', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('valor_causa', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('suspenso', 'Suspenso'), ('sobrestado', 'Sobrestado'), ('encerrado', 'Encerrado'), ('arquivado', 'Arquivado')], default='ativo', max_length=20)),
                ('fase', models.CharField(choices=[('conhecimento', 'Conhecimento'), ('recursal', 'Recursal'), ('cumprimento_sentenca', 'Cumprimento de Sentença'), ('execucao_extrajudicial', 'Execução'), ('outro', 'Outro')], default='conhecimento', max_length=30)),
                ('fase_andamento_atual', models.CharField(blank=True, choices=[('aguardando_retorno_citacao', 'Aguardando retorno de citação'), ('prazo_contestacao', 'Em prazo de contestação'), ('prazo_replica', 'Em prazo de réplica'), ('aguardando_decisao_tutela', 'Aguardando decisão de tutela'), ('aguardando_audiencia', 'Aguardando audiência'), ('alegacoes_finais', 'Em alegações finais'), ('aguardando_sentenca', 'Aguardando sentença'), ('aguardando_transito_julgado', 'Aguardando trânsito em julgado'), ('aguardando_expedicao_oficio', 'Aguardando expedição de ofício'), ('prazo_contrarrazoes', 'Em prazo de contrarrazões'), ('aguardando_decisao', 'Aguardando decisão'), ('aguardando_resultado_buscas', 'Aguardando resultado de buscas'), ('aguardando_restricao_bens', 'Aguardando restrição de bens'), ('aguardando_pericia', 'Aguardando perícia'), ('aguardando_laudo_pericial', 'Aguardando laudo pericial'), ('aguardando_alvara', 'Aguardando alvará')], max_length=40, verbose_name='Fase do andamento atual')),
                ('gratuidade_justica_status', models.CharField(choices=[('nao_requerida', 'Não Requerida'), ('requerida', 'Requerida'), ('deferida', 'Deferida'), ('indeferida', 'Indeferida'), ('revogada', 'Revogada')], default='nao_requerida', max_length=20)),
                ('resultado_sentenca', models.CharField(blank=True, choices=[('procedente', 'Procedente'), ('parcialmente_procedente', 'Parcialmente procedente'), ('improcedente', 'Improcedente')], max_length=30)),
                ('data_distribuicao', models.DateField(blank=True, null=True)),
                ('prazo_proximo', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('clientes', models.ManyToManyField(blank=True, related_name='processos', to='clientes.cliente')),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to='accounts.equipe', verbose_name='Equipe')),
                ('integrantes_habilitados', models.ManyToManyField(blank=True, related_name='processos_integrante_habilitado', to=settings.AUTH_USER_MODEL, verbose_name='Integrantes habilitados')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ParteProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('autor', 'Autor'), ('embargante', 'Embargante'), ('recorrente', 'Recorrente'), ('exequente', 'Exequente'), ('requerente', 'Requerente'), ('reclamante', 'Reclamante'), ('agravante', 'Agravante'), ('impugnante', 'Impugnante'), ('reconvinte', 'Reconvinte'), ('excipiente', 'Excipiente'), ('impetrante', 'Impetrante'), ('inventariante', 'Inventariante'), ('reu', 'Réu'), ('embargado', 'Embargado'), ('recorrido', 'Recorrido'), ('executado', 'Executado'), ('requerido', 'Requerido'), ('reclamado', 'Reclamado'), ('agravado', 'Agravado'), ('impugnado', 'Impugnado'), ('reconvindo', 'Reconvindo'), ('excepto', 'Excepto'), ('impetrado', 'Impetrado'), ('inventariado', 'Inventariado'), ('terceiro_interessado', 'Terceiro Interessado'), ('ministerio_publico', 'Ministério Público'), ('juiz', 'Juiz'), ('perito', 'Perito'), ('testemunha', 'Testemunha'), ('assistente_acusacao', 'Assistente de Acusação')], max_length=30)),
                ('nome', models.CharField(max_length=255)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=18)),
                ('advogado_nome', models.CharField(blank=True, max_length=255)),
                ('advogado_oab', models.CharField(blank=True, max_length=30)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='processos.processo')),
            ],
            options={
                'verbose_name': 'Parte do Processo',
                'verbose_name_plural': 'Partes do Processo',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoProcessual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('andamento', 'Andamento'), ('decisao', 'Decisão'), ('audiencia', 'Audiência'), ('outro', 'Outro'), ('despacho', 'Despacho'), ('decisao_interlocutoria', 'Decisão interlocutória'), ('pericia', 'Perícia'), ('peticao_inicial', 'Petição inicial'), ('expedicao_de_mandado', 'Expedição de mandado (citação, penhora, avaliação, levantamento de valores, carta precatória)'), ('retorno_de_citacao', 'Retorno de citação'), ('intimacao', 'Intimação'), ('contestacao', 'Contestação'), ('reconvencao', 'Reconvenção'), ('excecao_de_pre_executividade', 'Exceção de pré-executividade'), ('replica', 'Réplica'), ('quesitos_tecnicos', 'Quesitos técnicos'), ('ata_de_audiencia', 'Ata de audiência'), ('alegacoes_finais', 'Alegações finais'), ('sentenca', 'Sentença'), ('embargos_de_declaracao', 'Embargos de declaração'), ('apelacao', 'Apelação'), ('contrarrazoes', 'Contrarrazões'), ('agravo_de_instrumento', 'Agravo de instrumento'), ('agravo_interno', 'Agravo interno'), ('recurso_adesivo', 'Recurso adesivo'), ('acordao', 'Acórdão'), ('recurso_especial', 'Recurso especial (STJ)'), ('recurso_extraordinario', 'Recurso extraordinário (STF)'), ('agravo_em_recurso_especial_extraordinario', 'Agravo em recurso especial/extraordinário'), ('embargos_de_divergencia', 'Embargos de divergência'), ('peticao', 'Petição (mero expediente)'), ('juntada_de_documento', 'Juntada de documento'), ('certidao', 'Certidão'), ('homologacao', 'Homologação (acordo, transação, cálculos)'), ('transito_em_julgado', 'Trânsito em julgado'), ('cumprimento_de_sentenca_execucao', 'Cumprimento de sentença/execução'), ('impugnacao', 'Impugnação'), ('penhora_constricao_de_bens', 'Penhora/constrição de bens'), ('arquivamento', 'Arquivamento'), ('desarquivamento', 'Desarquivamento'), ('reclamacao_trabalhista', 'Reclamação trabalhista (petição inicial)'), ('retorno_de_citacao_notificacao_inicial', 'Retorno de citação (notificação inicial)'), ('razoes_finais', 'Razões finais'), ('recurso_ordinario', 'Recurso ordinário (RO)'), ('recurso_de_revista', 'Recurso de revista (RR)'), ('embargos_ao_tst', 'Embargos ao TST'), ('liquidacao_de_sentenca', 'Liquidação de sentença'), ('execucao', 'Execução'), ('agravo_de_peticao', 'Agravo de petição'), ('habilitacao_de_credito', 'Habilitação de crédito (falência/recuperação judicial do executado)'), ('inquerito_policial_termo_circunstanciado', 'Inquérito policial/termo circunstanciado'), ('denuncia_queixa_crime', 'Denúncia/queixa-crime'), ('decisao_recebimento_rejeicao_denuncia', 'Decisão (recebimento ou rejeição da denúncia/queixa)'), ('expedicao_de_mandado_penal', 'Expedição de mandado (citação, busca e apreensão, prisão)'), ('resposta_a_acusacao', 'Resposta à acusação'), ('replica_rito_juri', 'Réplica (rito do Júri — art. 409 CPP)'), ('decisao_absolvicao_sumaria', 'Decisão (absolvição sumária)'), ('pronuncia_impronuncia', 'Pronúncia/impronúncia (rito do Júri)'), ('ata_de_audiencia_instrucao_julgamento', 'Ata de audiência (instrução e julgamento)'), ('interrogatorio', 'Interrogatório'), ('recurso_em_sentido_estrito', 'Recurso em sentido estrito (RESE)'), ('carta_testemunhavel', 'Carta testemunhável'), ('habeas_corpus', 'Habeas corpus'), ('embargos_infringentes_ou_de_nulidade', 'Embargos infringentes ou de nulidade'), ('revisao_criminal', 'Revisão criminal (ação autônoma, não recurso técnico — incluída na fase recursal por praticidade)'), ('sessao_de_julgamento', 'Sessão de julgamento (Plenário do Júri)'), ('homologacao_penal', 'Homologação (transação penal, suspensão condicional do processo)'), ('guia_de_execucao_penal', 'Guia de execução penal'), ('progressao_regressao_de_regime', 'Progressão/regressão de regime'), ('livramento_condicional', 'Livramento condicional'), ('remicao_de_pena', 'Remição de pena'), ('agravo_em_execucao', 'Agravo em execução'), ('extincao_da_punibilidade', 'Extinção da punibilidade'), ('arquivamento_inquerito', 'Arquivamento (do inquérito ou definitivo dos autos)')], default='andamento', max_length=60)),
                ('data_prazo', models.DateField(blank=True, null=True, verbose_name='Prazo')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('origem_prazo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prazos_originados', to='processos.movimentacaoprocessual', verbose_name='Andamento de origem do prazo')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='processos.processo')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Intimacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=255)),
                ('prazo_manifestacao', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('manifestada', 'Manifestada')], default='pendente', max_length=20)),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('email', 'E-mail')], default='manual', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intimacoes', to='processos.processo')),
            ],
            options={
                'verbose_name': 'Intimação',
                'verbose_name_plural': 'Intimações',
                'ordering': ['prazo_manifestacao'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(storage=apps.saas_tenants.storage.StorageProtegido(), upload_to=apps.saas_tenants.storage.CaminhoArquivoTenant('protegido', 'processos/documentos'))),
                ('tipo', models.CharField(choices=[('peticao', 'Petição'), ('decisao', 'Decisão'), ('procuracao', 'Procuração'), ('prova', 'Prova'), ('contrato', 'Contrato'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='processos.processo')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-enviado_em'],
            },
        ),
        migrations.CreateModel(
            name='VinculoProcessoApenso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('processo_maior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_apensos_como_maior', to='processos.processo')),
                ('processo_menor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_apensos_como_menor', to='processos.processo')),
            ],
            options={
                'verbose_name': 'Vínculo de processo apenso',
                'verbose_name_plural': 'Vínculos de processos apensos',
                'constraints': [models.CheckConstraint(condition=models.Q(('processo_menor_id__lt', models.F('processo_maior_id'))), name='processos_apenso_ordem_valida'), models.UniqueConstraint(fields=('processo_menor', 'processo_maior'), name='processos_apenso_par_unico')],
            },
        ),
    ]
