# Generated by Django 5.2.15 on 2026-06-08 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('numero', models.CharField(blank=True, max_length=50)),
                ('area_direito', models.CharField(choices=[('CÍVEL', 'Cível'), ('CONSUMIDOR', 'Consumidor'), ('TRABALHISTA', 'Trabalhista'), ('SUCESSÕES', 'Sucessões'), ('CRIMINAL', 'Criminal'), ('ADMINISTRATIVO', 'Administrativo'), ('TRIBUTÁRIO', 'Tributário'), ('FAMÍLIA', 'Família'), ('OUTRO', 'Outro')], default='CÍVEL', max_length=30)),
                ('instancia', models.CharField(blank=True, default='1ª Instância', max_length=50)),
                ('vara_juizo', models.CharField(blank=True, max_length=255)),
                ('valor_causa', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('suspenso', 'Suspenso'), ('encerrado', 'Encerrado'), ('arquivado', 'Arquivado')], default='ativo', max_length=20)),
                ('prazo_proximo', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to='clientes.cliente')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ParteProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('autor', 'Autor'), ('reu', 'Réu'), ('terceiro', 'Terceiro'), ('advogado_contrario', 'Advogado Contrário')], default='autor', max_length=30)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=18)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='processos.processo')),
            ],
            options={
                'verbose_name': 'Parte do Processo',
                'verbose_name_plural': 'Partes do Processo',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoProcessual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('andamento', 'Andamento'), ('prazo', 'Prazo'), ('decisao', 'Decisão'), ('audiencia', 'Audiência'), ('outro', 'Outro')], default='andamento', max_length=20)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='processos.processo')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-data'],
            },
        ),
    ]
