# Generated by Django 5.2.15 on 2026-06-26 20:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='data_distribuicao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='fase',
            field=models.CharField(choices=[('conhecimento', 'Conhecimento'), ('recursal', 'Recursal'), ('cumprimento_sentenca', 'Cumprimento de Sentença'), ('execucao_extrajudicial', 'Execução Extrajudicial'), ('monitoria', 'Monitória'), ('outro', 'Outro')], default='conhecimento', max_length=30),
        ),
        migrations.AddField(
            model_name='processo',
            name='gratuidade_justica_status',
            field=models.CharField(choices=[('nao_requerida', 'Não Requerida'), ('requerida', 'Requerida'), ('deferida', 'Deferida'), ('indeferida', 'Indeferida'), ('revogada', 'Revogada')], default='nao_requerida', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimentacaoprocessual',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
