# Generated by Django 5.2.15 on 2026-09-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0003_numero_interno_obrigatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='parteprocesso',
            name='ente_publico',
            field=models.CharField(blank=True, choices=[('federal', 'Federal (União, autarquias e fundações federais)'), ('estadual', 'Estadual/DF (Estado, DF, autarquias e fundações)'), ('municipal', 'Municipal (Município, autarquias e fundações)')], max_length=10, verbose_name='Ente público'),
        ),
    ]
