# Generated by Django 5.2.15 on 2026-09-26 14:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0004_ente_publico_parte'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoAcompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciada_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('falhas', models.PositiveIntegerField(default=0)),
                ('erro', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Execução do acompanhamento',
                'verbose_name_plural': 'Execuções do acompanhamento',
                'ordering': ['-iniciada_em'],
            },
        ),
        migrations.AddField(
            model_name='movimentacaoprocessual',
            name='destinatarios',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movimentacaoprocessual',
            name='fonte',
            field=models.CharField(blank=True, choices=[('djen', 'DJEN'), ('datajud', 'DataJud')], max_length=10),
        ),
        migrations.AddField(
            model_name='movimentacaoprocessual',
            name='link',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='movimentacaoprocessual',
            name='prazo_a_definir',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimentacaoprocessual',
            name='prazo_calculado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimentacaoprocessual',
            name='prazo_de',
            field=models.CharField(choices=[('nosso_cliente', 'Nosso cliente'), ('outra_parte', 'Outra parte')], default='nosso_cliente', max_length=20, verbose_name='Prazo de'),
        ),
        migrations.AddField(
            model_name='movimentacaoprocessual',
            name='prazo_dias',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaoprocessual',
            name='prazo_dobrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimentacaoprocessual',
            name='sugerido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parteprocesso',
            name='prazo_em_dobro',
            field=models.BooleanField(default=False, verbose_name='Prazo em dobro'),
        ),
        migrations.AddField(
            model_name='processo',
            name='segredo_justica',
            field=models.BooleanField(default=False, verbose_name='Segredo de justiça'),
        ),
        migrations.CreateModel(
            name='AcompanhamentoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('djen_consultado_ate', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('processo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhamento', to='processos.processo')),
            ],
            options={
                'verbose_name': 'Acompanhamento de processo',
                'verbose_name_plural': 'Acompanhamentos de processo',
            },
        ),
        migrations.CreateModel(
            name='ComunicacaoDjen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=100, unique=True)),
                ('comunicacao_id', models.BigIntegerField()),
                ('chave_grupo', models.CharField(max_length=64)),
                ('data_disponibilizacao', models.DateField()),
                ('link', models.URLField(blank=True, max_length=1000)),
                ('anterior_ao_acompanhamento', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('movimentacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicacoes_djen', to='processos.movimentacaoprocessual')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicacoes_djen', to='processos.processo')),
            ],
            options={
                'verbose_name': 'Comunicação do DJEN',
                'verbose_name_plural': 'Comunicações do DJEN',
                'ordering': ['-data_disponibilizacao'],
            },
        ),
    ]
