# Generated by Django 5.2.15 on 2026-09-26 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0005_acompanhamento_djen'),
    ]

    operations = [
        migrations.AddField(
            model_name='acompanhamentoprocesso',
            name='datajud_consultado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acompanhamentoprocesso',
            name='datajud_encontrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acompanhamentoprocesso',
            name='datajud_grau',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='acompanhamentoprocesso',
            name='datajud_orgao_julgador',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='acompanhamentoprocesso',
            name='djen_consultado_ate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MovimentoDatajud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('movimentacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_datajud', to='processos.movimentacaoprocessual')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos_datajud', to='processos.processo')),
            ],
            options={
                'verbose_name': 'Movimento do DataJud',
                'verbose_name_plural': 'Movimentos do DataJud',
                'constraints': [models.UniqueConstraint(fields=('processo', 'chave'), name='movimento_datajud_unico_por_processo')],
            },
        ),
    ]
