# Generated by Django 5.2.15 on 2026-09-26 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0006_acompanhamento_datajud'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicacaodjen',
            name='cancelada_em',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaoprocessual',
            name='prazo_a_definir_avisado_em',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NumeroCnjCitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros_cnj_citados', to='processos.processo')),
            ],
            options={
                'verbose_name': 'Número CNJ citado',
                'verbose_name_plural': 'Números CNJ citados',
                'ordering': ['criado_em'],
                'constraints': [models.UniqueConstraint(fields=('processo', 'numero'), name='numero_cnj_citado_unico_por_processo')],
            },
        ),
    ]
