# Generated by Django 5.2.15 on 2026-09-26 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0008_titulo_maiusculas'),
    ]

    operations = [
        migrations.AddField(
            model_name='parteprocesso',
            name='gratuidade_justica',
            field=models.BooleanField(default=False, verbose_name='Gratuidade de justiça'),
        ),
        migrations.CreateModel(
            name='RepresentanteParte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('qualificacao', models.CharField(choices=[('socio_administrador', 'Sócio/Administrador'), ('pai_mae', 'Pai/Mãe'), ('tutor', 'Tutor'), ('curador', 'Curador'), ('outro', 'Outro')], max_length=30, verbose_name='Qualificação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representantes', to='processos.parteprocesso')),
            ],
            options={
                'verbose_name': 'Representante da parte',
                'verbose_name_plural': 'Representantes da parte',
                'ordering': ['criado_em'],
            },
        ),
    ]
