# Generated by Django 5.2.15 on 2026-09-02 00:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0011_simplificar_partes_processo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='integrantes_habilitados',
            field=models.ManyToManyField(blank=True, related_name='processos_integrante_habilitado', to=settings.AUTH_USER_MODEL, verbose_name='Integrantes habilitados'),
        ),
    ]
