# Generated by Django 5.2.15 on 2026-09-11 23:13

import apps.saas_tenants.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0012_processo_integrantes_habilitados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(storage=apps.saas_tenants.storage.StorageProtegido(), upload_to=apps.saas_tenants.storage.CaminhoArquivoTenant('protegido', 'processos/documentos'))),
                ('tipo', models.CharField(choices=[('peticao', 'Petição'), ('decisao', 'Decisão'), ('procuracao', 'Procuração'), ('prova', 'Prova'), ('contrato', 'Contrato'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='processos.processo')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-enviado_em'],
            },
        ),
    ]
