# Generated by Django 5.2.15 on 2026-09-13 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0014_processo_cidade_processo_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intimacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=255)),
                ('prazo_manifestacao', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('manifestada', 'Manifestada')], default='pendente', max_length=20)),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('email', 'E-mail')], default='manual', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intimacoes', to='processos.processo')),
            ],
            options={
                'verbose_name': 'Intimação',
                'verbose_name_plural': 'Intimações',
                'ordering': ['prazo_manifestacao'],
            },
        ),
    ]
