# Generated by Django 5.2.15 on 2026-09-14 15:48
# Ajustada manualmente (reunião de 13/09): separa vara_juizo em vara +
# comarca preservando o dado existente, e normaliza fase="monitoria"
# (removida do catálogo) para "outro" em vez de deixar um código órfão.

from django.db import migrations, models


def copiar_vara_juizo_para_vara(apps, schema_editor):
    Processo = apps.get_model("processos", "Processo")
    Processo.objects.exclude(vara_juizo="").update(vara=models.F("vara_juizo"))


def copiar_vara_para_vara_juizo(apps, schema_editor):
    Processo = apps.get_model("processos", "Processo")
    Processo.objects.exclude(vara="").update(vara_juizo=models.F("vara"))


def normalizar_fase_monitoria(apps, schema_editor):
    Processo = apps.get_model("processos", "Processo")
    Processo.objects.filter(fase="monitoria").update(fase="outro")


def noop_reverso(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0015_intimacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='comarca',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='processo',
            name='vara',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(copiar_vara_juizo_para_vara, copiar_vara_para_vara_juizo),
        migrations.RemoveField(
            model_name='processo',
            name='vara_juizo',
        ),
        migrations.RunPython(normalizar_fase_monitoria, noop_reverso),
        migrations.AlterField(
            model_name='parteprocesso',
            name='papel',
            field=models.CharField(choices=[('autor', 'Autor'), ('embargante', 'Embargante'), ('recorrente', 'Recorrente'), ('exequente', 'Exequente'), ('requerente', 'Requerente'), ('reclamante', 'Reclamante'), ('agravante', 'Agravante'), ('impugnante', 'Impugnante'), ('reconvinte', 'Reconvinte'), ('excipiente', 'Excipiente'), ('impetrante', 'Impetrante'), ('inventariante', 'Inventariante'), ('reu', 'Réu'), ('embargado', 'Embargado'), ('recorrido', 'Recorrido'), ('executado', 'Executado'), ('requerido', 'Requerido'), ('reclamado', 'Reclamado'), ('agravado', 'Agravado'), ('impugnado', 'Impugnado'), ('reconvindo', 'Reconvindo'), ('excepto', 'Excepto'), ('impetrado', 'Impetrado'), ('inventariado', 'Inventariado'), ('terceiro_interessado', 'Terceiro Interessado'), ('ministerio_publico', 'Ministério Público'), ('juiz', 'Juiz')], max_length=30),
        ),
        migrations.AlterField(
            model_name='processo',
            name='area_direito',
            field=models.CharField(choices=[('CÍVEL', 'Cível'), ('CONSUMIDOR', 'Consumidor'), ('TRABALHISTA', 'Trabalhista'), ('SUCESSÕES', 'Sucessões'), ('CRIMINAL', 'Penal'), ('ADMINISTRATIVO', 'Administrativo'), ('TRIBUTÁRIO', 'Tributário'), ('FAMÍLIA', 'Família'), ('OUTRO', 'Outro')], default='CÍVEL', max_length=30),
        ),
        migrations.AlterField(
            model_name='processo',
            name='fase',
            field=models.CharField(choices=[('conhecimento', 'Conhecimento'), ('recursal', 'Recursal'), ('cumprimento_sentenca', 'Cumprimento de Sentença'), ('execucao_extrajudicial', 'Execução'), ('outro', 'Outro')], default='conhecimento', max_length=30),
        ),
    ]
