# Generated by Django 5.2.15 on 2026-09-14 19:46
# Ajustada manualmente (reunião de 13/09): Processo.cliente (FK única)
# vira Processo.clientes (M2M), preservando o cliente já vinculado.
# Sequência: adiciona o M2M com related_name temporário (para não colidir
# com o related_name "processos" da FK antiga, que ainda existe nesse
# momento) -> copia o dado -> remove a FK antiga -> só então renomeia o
# related_name do M2M para o definitivo "processos".

from django.db import migrations, models


def copiar_cliente_para_clientes(apps, schema_editor):
    Processo = apps.get_model("processos", "Processo")
    for processo in Processo.objects.filter(cliente_id__isnull=False):
        processo.clientes.add(processo.cliente_id)


def copiar_clientes_para_cliente(apps, schema_editor):
    Processo = apps.get_model("processos", "Processo")
    for processo in Processo.objects.prefetch_related("clientes").all():
        primeiro = processo.clientes.first()
        if primeiro is not None:
            processo.cliente_id = primeiro.pk
            processo.save(update_fields=["cliente_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_cliente_responsavel_obrigatorio'),
        ('processos', '0016_remove_processo_vara_juizo_processo_comarca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='clientes',
            field=models.ManyToManyField(blank=True, related_name='processos_clientes_tmp', to='clientes.cliente'),
        ),
        migrations.RunPython(copiar_cliente_para_clientes, copiar_clientes_para_cliente),
        migrations.RemoveField(
            model_name='processo',
            name='cliente',
        ),
        migrations.AlterField(
            model_name='processo',
            name='clientes',
            field=models.ManyToManyField(blank=True, related_name='processos', to='clientes.cliente'),
        ),
    ]
