# Generated by Django 5.2.15 on 2026-09-16 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0017_remove_processo_cliente_processo_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoprocessual',
            name='data_prazo',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo'),
        ),
        migrations.AddField(
            model_name='movimentacaoprocessual',
            name='origem_prazo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prazos_originados', to='processos.movimentacaoprocessual', verbose_name='Andamento de origem do prazo'),
        ),
        migrations.AlterField(
            model_name='movimentacaoprocessual',
            name='tipo',
            field=models.CharField(choices=[('andamento', 'Andamento'), ('decisao', 'Decisão'), ('audiencia', 'Audiência'), ('outro', 'Outro'), ('despacho', 'Despacho'), ('decisao_interlocutoria', 'Decisão interlocutória'), ('pericia', 'Perícia'), ('peticao_inicial', 'Petição inicial'), ('expedicao_de_mandado', 'Expedição de mandado (citação, penhora, avaliação, levantamento de valores, carta precatória)'), ('retorno_de_citacao', 'Retorno de citação'), ('intimacao', 'Intimação'), ('contestacao', 'Contestação'), ('reconvencao', 'Reconvenção'), ('excecao_de_pre_executividade', 'Exceção de pré-executividade'), ('replica', 'Réplica'), ('quesitos_tecnicos', 'Quesitos técnicos'), ('ata_de_audiencia', 'Ata de audiência'), ('alegacoes_finais', 'Alegações finais'), ('sentenca', 'Sentença'), ('embargos_de_declaracao', 'Embargos de declaração'), ('apelacao', 'Apelação'), ('contrarrazoes', 'Contrarrazões'), ('agravo_de_instrumento', 'Agravo de instrumento'), ('agravo_interno', 'Agravo interno'), ('recurso_adesivo', 'Recurso adesivo'), ('acordao', 'Acórdão'), ('recurso_especial', 'Recurso especial (STJ)'), ('recurso_extraordinario', 'Recurso extraordinário (STF)'), ('agravo_em_recurso_especial_extraordinario', 'Agravo em recurso especial/extraordinário'), ('embargos_de_divergencia', 'Embargos de divergência'), ('peticao', 'Petição (mero expediente)'), ('juntada_de_documento', 'Juntada de documento'), ('certidao', 'Certidão'), ('homologacao', 'Homologação (acordo, transação, cálculos)'), ('transito_em_julgado', 'Trânsito em julgado'), ('cumprimento_de_sentenca_execucao', 'Cumprimento de sentença/execução'), ('impugnacao', 'Impugnação'), ('penhora_constricao_de_bens', 'Penhora/constrição de bens'), ('arquivamento', 'Arquivamento'), ('desarquivamento', 'Desarquivamento'), ('reclamacao_trabalhista', 'Reclamação trabalhista (petição inicial)'), ('retorno_de_citacao_notificacao_inicial', 'Retorno de citação (notificação inicial)'), ('razoes_finais', 'Razões finais'), ('recurso_ordinario', 'Recurso ordinário (RO)'), ('recurso_de_revista', 'Recurso de revista (RR)'), ('embargos_ao_tst', 'Embargos ao TST'), ('liquidacao_de_sentenca', 'Liquidação de sentença'), ('execucao', 'Execução'), ('agravo_de_peticao', 'Agravo de petição'), ('habilitacao_de_credito', 'Habilitação de crédito (falência/recuperação judicial do executado)'), ('inquerito_policial_termo_circunstanciado', 'Inquérito policial/termo circunstanciado'), ('denuncia_queixa_crime', 'Denúncia/queixa-crime'), ('decisao_recebimento_rejeicao_denuncia', 'Decisão (recebimento ou rejeição da denúncia/queixa)'), ('expedicao_de_mandado_penal', 'Expedição de mandado (citação, busca e apreensão, prisão)'), ('resposta_a_acusacao', 'Resposta à acusação'), ('replica_rito_juri', 'Réplica (rito do Júri — art. 409 CPP)'), ('decisao_absolvicao_sumaria', 'Decisão (absolvição sumária)'), ('pronuncia_impronuncia', 'Pronúncia/impronúncia (rito do Júri)'), ('ata_de_audiencia_instrucao_julgamento', 'Ata de audiência (instrução e julgamento)'), ('interrogatorio', 'Interrogatório'), ('recurso_em_sentido_estrito', 'Recurso em sentido estrito (RESE)'), ('carta_testemunhavel', 'Carta testemunhável'), ('habeas_corpus', 'Habeas corpus'), ('embargos_infringentes_ou_de_nulidade', 'Embargos infringentes ou de nulidade'), ('revisao_criminal', 'Revisão criminal (ação autônoma, não recurso técnico — incluída na fase recursal por praticidade)'), ('sessao_de_julgamento', 'Sessão de julgamento (Plenário do Júri)'), ('homologacao_penal', 'Homologação (transação penal, suspensão condicional do processo)'), ('guia_de_execucao_penal', 'Guia de execução penal'), ('progressao_regressao_de_regime', 'Progressão/regressão de regime'), ('livramento_condicional', 'Livramento condicional'), ('remicao_de_pena', 'Remição de pena'), ('agravo_em_execucao', 'Agravo em execução'), ('extincao_da_punibilidade', 'Extinção da punibilidade'), ('arquivamento_inquerito', 'Arquivamento (do inquérito ou definitivo dos autos)')], default='andamento', max_length=60),
        ),
    ]
