# Generated by Django 5.2.15 on 2026-09-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0019_migrar_tipo_prazo_para_data_prazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parteprocesso',
            name='papel',
            field=models.CharField(choices=[('autor', 'Autor'), ('embargante', 'Embargante'), ('recorrente', 'Recorrente'), ('exequente', 'Exequente'), ('requerente', 'Requerente'), ('reclamante', 'Reclamante'), ('agravante', 'Agravante'), ('impugnante', 'Impugnante'), ('reconvinte', 'Reconvinte'), ('excipiente', 'Excipiente'), ('impetrante', 'Impetrante'), ('inventariante', 'Inventariante'), ('reu', 'Réu'), ('embargado', 'Embargado'), ('recorrido', 'Recorrido'), ('executado', 'Executado'), ('requerido', 'Requerido'), ('reclamado', 'Reclamado'), ('agravado', 'Agravado'), ('impugnado', 'Impugnado'), ('reconvindo', 'Reconvindo'), ('excepto', 'Excepto'), ('impetrado', 'Impetrado'), ('inventariado', 'Inventariado'), ('terceiro_interessado', 'Terceiro Interessado'), ('ministerio_publico', 'Ministério Público'), ('juiz', 'Juiz'), ('perito', 'Perito'), ('testemunha', 'Testemunha'), ('assistente_acusacao', 'Assistente de Acusação')], max_length=30),
        ),
    ]
