# Generated by Django 5.2.15 on 2026-09-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0020_alter_parteprocesso_papel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='area_direito',
            field=models.CharField(choices=[('CÍVEL', 'Cível'), ('CONSUMIDOR', 'Consumidor'), ('TRABALHISTA', 'Trabalhista'), ('SUCESSÕES', 'Sucessões'), ('CRIMINAL', 'Penal'), ('ADMINISTRATIVO', 'Administrativo'), ('TRIBUTÁRIO', 'Tributário'), ('FAMÍLIA', 'Família'), ('EMPRESARIAL', 'Empresarial'), ('ELEITORAL', 'Eleitoral'), ('MÉDICO', 'Médico'), ('PREVIDENCIÁRIO', 'Previdenciário'), ('DIGITAL', 'Digital'), ('PROPRIEDADE_INTELECTUAL', 'Propriedade Intelectual'), ('IMOBILIÁRIO', 'Imobiliário'), ('DESPORTIVO', 'Desportivo'), ('DIREITO_INTERNACIONAL', 'Direito Internacional'), ('OUTRO', 'Outro')], default='CÍVEL', max_length=30),
        ),
    ]
