# Generated by Django 5.2.15 on 2026-09-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0021_alter_processo_area_direito'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='fase_andamento_atual',
            field=models.CharField(blank=True, choices=[('aguardando_retorno_citacao', 'Aguardando retorno de citação'), ('prazo_contestacao', 'Em prazo de contestação'), ('prazo_replica', 'Em prazo de réplica'), ('aguardando_decisao_tutela', 'Aguardando decisão de tutela'), ('aguardando_audiencia', 'Aguardando audiência'), ('alegacoes_finais', 'Em alegações finais'), ('aguardando_sentenca', 'Aguardando sentença'), ('aguardando_transito_julgado', 'Aguardando trânsito em julgado'), ('aguardando_expedicao_oficio', 'Aguardando expedição de ofício'), ('prazo_contrarrazoes', 'Em prazo de contrarrazões'), ('aguardando_decisao', 'Aguardando decisão'), ('aguardando_resultado_buscas', 'Aguardando resultado de buscas'), ('aguardando_restricao_bens', 'Aguardando restrição de bens'), ('aguardando_pericia', 'Aguardando perícia'), ('aguardando_laudo_pericial', 'Aguardando laudo pericial'), ('aguardando_alvara', 'Aguardando alvará')], max_length=40, verbose_name='Fase do andamento atual'),
        ),
    ]
