# Generated by Django 5.2.15 on 2026-09-19 20:42

from django.db import migrations, models


def converter_eleitoral_para_outro(apps, schema_editor):
    Processo = apps.get_model("processos", "Processo")
    Processo.objects.filter(area_direito="ELEITORAL").update(area_direito="OUTRO")


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0022_processo_fase_andamento_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='area_direito',
            field=models.CharField(choices=[('CÍVEL', 'Cível'), ('CONSUMIDOR', 'Consumidor'), ('TRABALHISTA', 'Trabalhista'), ('SUCESSÕES', 'Sucessões'), ('CRIMINAL', 'Penal'), ('ADMINISTRATIVO', 'Administrativo'), ('TRIBUTÁRIO', 'Tributário'), ('FAMÍLIA', 'Família'), ('EMPRESARIAL', 'Empresarial'), ('MÉDICO', 'Médico'), ('PREVIDENCIÁRIO', 'Previdenciário'), ('DIGITAL', 'Digital'), ('PROPRIEDADE_INTELECTUAL', 'Propriedade Intelectual'), ('IMOBILIÁRIO', 'Imobiliário'), ('DESPORTIVO', 'Desportivo'), ('DIREITO_INTERNACIONAL', 'Direito Internacional'), ('OUTRO', 'Outro')], default='CÍVEL', max_length=30),
        ),
        # Reversa no-op: a informação "era Eleitoral" não é recuperável.
        migrations.RunPython(converter_eleitoral_para_outro, migrations.RunPython.noop),
    ]
