# Generated by Django 5.2.15 on 2026-09-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0023_remover_area_eleitoral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('suspenso', 'Suspenso'), ('sobrestado', 'Sobrestado'), ('encerrado', 'Encerrado'), ('arquivado', 'Arquivado')], default='ativo', max_length=20),
        ),
    ]
