# Generated by Django 5.2.15 on 2026-09-22 19:23

import apps.saas_tenants.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2)),
                ('nome_razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, verbose_name='Nome fantasia')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=18)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('estrangeiro', models.BooleanField(default=False, verbose_name='Estrangeiro')),
                ('nacionalidade', models.CharField(blank=True, choices=[('Brasileira', 'Brasileira'), ('Alemã', 'Alemã'), ('Americana', 'Americana'), ('Angolana', 'Angolana'), ('Argentina', 'Argentina'), ('Australiana', 'Australiana'), ('Austríaca', 'Austríaca'), ('Belga', 'Belga'), ('Boliviana', 'Boliviana'), ('Canadense', 'Canadense'), ('Chilena', 'Chilena'), ('Chinesa', 'Chinesa'), ('Colombiana', 'Colombiana'), ('Coreana', 'Coreana'), ('Cubana', 'Cubana'), ('Dinamarquesa', 'Dinamarquesa'), ('Egípcia', 'Egípcia'), ('Equatoriana', 'Equatoriana'), ('Espanhola', 'Espanhola'), ('Filipina', 'Filipina'), ('Francesa', 'Francesa'), ('Grega', 'Grega'), ('Holandesa', 'Holandesa'), ('Húngara', 'Húngara'), ('Indiana', 'Indiana'), ('Inglesa', 'Inglesa'), ('Iraniana', 'Iraniana'), ('Irlandesa', 'Irlandesa'), ('Israelense', 'Israelense'), ('Italiana', 'Italiana'), ('Japonesa', 'Japonesa'), ('Libanesa', 'Libanesa'), ('Marroquina', 'Marroquina'), ('Mexicana', 'Mexicana'), ('Moçambicana', 'Moçambicana'), ('Norueguesa', 'Norueguesa'), ('Paraguaia', 'Paraguaia'), ('Peruana', 'Peruana'), ('Polonesa', 'Polonesa'), ('Portuguesa', 'Portuguesa'), ('Russa', 'Russa'), ('Sueca', 'Sueca'), ('Suíça', 'Suíça'), ('Sul-africana', 'Sul-africana'), ('Uruguaia', 'Uruguaia'), ('Venezuelana', 'Venezuelana'), ('Outra', 'Outra')], default='Brasileira', max_length=100)),
                ('estado_civil', models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('uniao_estavel', 'União Estável'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('separado', 'Separado(a) judicialmente')], max_length=20)),
                ('profissao', models.CharField(blank=True, max_length=100)),
                ('rg', models.CharField(blank=True, max_length=20, verbose_name='RG')),
                ('data_nascimento', models.DateField(blank=True, help_text='Só para Pessoa Física — usada para calcular a idade, nunca digitada diretamente.', null=True, verbose_name='Data de nascimento')),
                ('representante_nome', models.CharField(blank=True, max_length=255, verbose_name='Nome do representante')),
                ('representante_cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF do representante')),
                ('representante_cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo/qualificação do representante')),
                ('representante_telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone do representante')),
                ('representante_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail do representante')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes_responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome_razao_social'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(storage=apps.saas_tenants.storage.StorageProtegido(), upload_to=apps.saas_tenants.storage.CaminhoArquivoTenant('protegido', 'clientes/documentos'))),
                ('tipo', models.CharField(choices=[('identificacao', 'Documento de identificação'), ('comprovante_residencia', 'Comprovante de residência'), ('contrato_social', 'Contrato social'), ('procuracao', 'Procuração'), ('outro', 'Outro')], default='outro', max_length=30)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_cliente_autor', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-enviado_em'],
            },
        ),
    ]
