# Generated by Django 5.2.15 on 2026-07-15 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_departamento_membrodepartamento'),
        ('clientes', '0003_cliente_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='accounts.departamento', verbose_name='Departamento'),
        ),
    ]
