# Generated by Django 5.2.15 on 2026-07-18 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='departamento',
        ),
    ]
