# Generated by Django 5.2.15 on 2026-09-14 23:03
# Ajustada manualmente (reunião de 13/09): endereço estruturado
# substitui o campo único `endereco` — copia o texto livre existente
# para `logradouro` (melhor esforço, truncado ao novo max_length) antes
# de remover o campo antigo, para não perder dado já cadastrado.

from django.db import migrations, models


def copiar_endereco_para_logradouro(apps, schema_editor):
    Cliente = apps.get_model("clientes", "Cliente")
    for cliente in Cliente.objects.exclude(endereco=""):
        cliente.logradouro = (cliente.endereco or "")[:255]
        cliente.save(update_fields=["logradouro"])


def copiar_logradouro_para_endereco(apps, schema_editor):
    Cliente = apps.get_model("clientes", "Cliente")
    Cliente.objects.exclude(logradouro="").update(endereco=models.F("logradouro"))


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_cliente_responsavel_obrigatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('uniao_estavel', 'União Estável'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('separado', 'Separado(a) judicialmente')], max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estrangeiro',
            field=models.BooleanField(default=False, verbose_name='Estrangeiro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nacionalidade',
            field=models.CharField(blank=True, choices=[('Brasileira', 'Brasileira'), ('Alemã', 'Alemã'), ('Americana', 'Americana'), ('Angolana', 'Angolana'), ('Argentina', 'Argentina'), ('Australiana', 'Australiana'), ('Austríaca', 'Austríaca'), ('Belga', 'Belga'), ('Boliviana', 'Boliviana'), ('Canadense', 'Canadense'), ('Chilena', 'Chilena'), ('Chinesa', 'Chinesa'), ('Colombiana', 'Colombiana'), ('Coreana', 'Coreana'), ('Cubana', 'Cubana'), ('Dinamarquesa', 'Dinamarquesa'), ('Egípcia', 'Egípcia'), ('Equatoriana', 'Equatoriana'), ('Espanhola', 'Espanhola'), ('Filipina', 'Filipina'), ('Francesa', 'Francesa'), ('Grega', 'Grega'), ('Holandesa', 'Holandesa'), ('Húngara', 'Húngara'), ('Indiana', 'Indiana'), ('Inglesa', 'Inglesa'), ('Iraniana', 'Iraniana'), ('Irlandesa', 'Irlandesa'), ('Israelense', 'Israelense'), ('Italiana', 'Italiana'), ('Japonesa', 'Japonesa'), ('Libanesa', 'Libanesa'), ('Marroquina', 'Marroquina'), ('Mexicana', 'Mexicana'), ('Moçambicana', 'Moçambicana'), ('Norueguesa', 'Norueguesa'), ('Paraguaia', 'Paraguaia'), ('Peruana', 'Peruana'), ('Polonesa', 'Polonesa'), ('Portuguesa', 'Portuguesa'), ('Russa', 'Russa'), ('Sueca', 'Sueca'), ('Suíça', 'Suíça'), ('Sul-africana', 'Sul-africana'), ('Uruguaia', 'Uruguaia'), ('Venezuelana', 'Venezuelana'), ('Outra', 'Outra')], default='Brasileira', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='profissao',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rg',
            field=models.CharField(blank=True, max_length=20, verbose_name='RG'),
        ),
        migrations.RunPython(copiar_endereco_para_logradouro, copiar_logradouro_para_endereco),
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
    ]
