# Generated by Django 5.2.15 on 2026-09-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='representante_cargo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cargo/qualificação do representante'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='representante_cpf',
            field=models.CharField(blank=True, max_length=14, verbose_name='CPF do representante'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='representante_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail do representante'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='representante_nome',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome do representante'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='representante_telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone do representante'),
        ),
    ]
