# Generated by Django 5.2.15 on 2026-09-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_cliente_representante_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_nascimento',
            field=models.DateField(blank=True, help_text='Só para Pessoa Física — usada para calcular a idade, nunca digitada diretamente.', null=True, verbose_name='Data de nascimento'),
        ),
    ]
