# Generated by Django 5.2.15 on 2026-09-22 19:23

import apps.saas_tenants.storage
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('processos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoCustas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grupo de custas',
                'verbose_name_plural': 'Grupos de custas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Honorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('contratual', 'Contratual'), ('sucumbencial', 'Sucumbência'), ('exito', 'Êxito'), ('outro', 'Outro')], max_length=20)),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_efetivo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('data_prevista', models.DateField(blank=True, null=True)),
                ('data_recebida', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('previsto', 'Previsto'), ('recebido', 'Recebido'), ('cancelado', 'Cancelado')], default='previsto', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('valor_recebido', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('taxa_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('data_termo', models.DateField(blank=True, null=True)),
                ('forma_condenacao', models.CharField(blank=True, choices=[('fixo', 'Valor fixo'), ('percentual', 'Percentual sobre a condenação'), ('fixo_percentual', 'Valor fixo + percentual')], max_length=16)),
                ('percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valor_condenacao', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('valor_fixo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('devedor_tipo', models.CharField(blank=True, choices=[('pessoa', 'Pessoa física ou jurídica'), ('ente_estatal', 'Ente estatal (União/Estado/Município)')], max_length=14)),
                ('indice_correcao', models.CharField(blank=True, choices=[('inpc', 'INPC (padrão legal)'), ('igpm', 'IGP-M (se previsto em contrato/sentença)'), ('selic', 'Taxa Selic (se previsto em contrato/sentença)'), ('ipca', 'IPCA (se previsto em contrato/sentença)')], max_length=6)),
                ('taxa_indice_mensal', models.DecimalField(blank=True, decimal_places=4, help_text='Taxa mensal (%) do índice escolhido, informada manualmente.', max_digits=6, null=True)),
                ('data_correcao', models.DateField(blank=True, null=True)),
                ('data_correcao_fim', models.DateField(blank=True, null=True)),
                ('data_juros', models.DateField(blank=True, null=True)),
                ('data_juros_fim', models.DateField(blank=True, null=True)),
                ('exito_percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('exito_valor_ganho', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('exito_data_correcao', models.DateField(blank=True, null=True)),
                ('modalidade', models.CharField(blank=True, choices=[('valor', 'Valor'), ('exito', 'Por êxito'), ('valor_exito', 'Valor + êxito')], max_length=12)),
                ('exito_base', models.CharField(blank=True, choices=[('ganho', 'Pelo ganho (atuo pelo autor/reconvindo)'), ('economia', 'Pela economia (atuo pelo réu)')], max_length=8)),
                ('classificacao', models.CharField(blank=True, choices=[('unica', 'Única'), ('parcelado', 'Parcelado'), ('recorrente', 'Recorrente')], max_length=12)),
                ('periodicidade', models.CharField(blank=True, choices=[('mensal', 'Mensal'), ('anual', 'Anual')], max_length=10)),
                ('numero_parcelas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duracao_tipo', models.CharField(blank=True, choices=[('quantidade', 'Quantidade de ocorrências'), ('data_final', 'Data final'), ('indeterminado', 'Indeterminado')], max_length=15)),
                ('duracao_quantidade', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duracao_data_final', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processos.processo')),
            ],
            options={
                'verbose_name': 'Honorário',
                'verbose_name_plural': 'Honorários',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('categoria', models.CharField(choices=[('honorario', 'Honorários'), ('honorario_sucumbencia', 'Honorários de sucumbência'), ('reembolso', 'Reembolso'), ('consultoria', 'Consultoria'), ('comissao', 'Comissão'), ('auditoria', 'Auditoria'), ('acordo', 'Acordo'), ('capacitacao', 'Capacitação'), ('aluguel', 'Aluguel'), ('condominio', 'Condomínio'), ('agua', 'Água'), ('luz', 'Luz'), ('internet', 'Internet'), ('salario', 'Salário'), ('bonificacao', 'Bonificação'), ('imposto', 'Impostos/taxas'), ('cursos', 'Cursos'), ('equipamentos', 'Equipamentos'), ('material', 'Material'), ('software', 'Software/assinatura'), ('outro', 'Outros'), ('exito', 'Honorário de Êxito'), ('solicitacao_pagamento', 'Solicitação de Pagamento'), ('custa_judicial', 'Custa Judicial'), ('diligencia', 'Diligência'), ('pericia', 'Perícia'), ('taxa', 'Taxa/Emolumento')], default='honorario', max_length=30)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('pix', 'Pix'), ('boleto', 'Boleto'), ('transferencia', 'Transferência'), ('dinheiro', 'Dinheiro'), ('cartao', 'Cartão'), ('outro', 'Outro')], max_length=20)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('anexo', models.FileField(blank=True, null=True, storage=apps.saas_tenants.storage.StorageProtegido(), upload_to=apps.saas_tenants.storage.CaminhoArquivoTenant('protegido', 'financeiro/lancamentos'))),
                ('comprovante_pagamento', models.FileField(blank=True, null=True, storage=apps.saas_tenants.storage.StorageProtegido(), upload_to=apps.saas_tenants.storage.CaminhoArquivoTenant('protegido', 'financeiro/lancamentos/comprovantes'))),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('classificacao', models.CharField(choices=[('unica', 'Única'), ('parcelado', 'Parcelado'), ('recorrente', 'Recorrente')], default='unica', max_length=12)),
                ('periodicidade', models.CharField(blank=True, choices=[('mensal', 'Mensal'), ('anual', 'Anual')], max_length=10)),
                ('numero_parcelas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duracao_tipo', models.CharField(blank=True, choices=[('quantidade', 'Quantidade de ocorrências'), ('data_final', 'Data final'), ('indeterminado', 'Indeterminado')], max_length=15)),
                ('duracao_quantidade', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duracao_data_final', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
                ('honorario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='financeiro.honorario')),
                ('lancamento_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='financeiro.lancamentofinanceiro')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processos.processo')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lançamento Financeiro',
                'verbose_name_plural': 'Lançamentos Financeiros',
                'ordering': ['data_vencimento', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='CustaJudicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('adiantamento', 'Adiantado pelo escritório'), ('paga_pelo_cliente', 'Paga diretamente pelo cliente'), ('deposito_cliente', 'Depósito do cliente')], max_length=20)),
                ('anexo', models.FileField(blank=True, null=True, storage=apps.saas_tenants.storage.StorageProtegido(), upload_to=apps.saas_tenants.storage.CaminhoArquivoTenant('protegido', 'financeiro/custas'))),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processos.processo')),
                ('reembolsada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reembolsa', to='financeiro.custajudicial')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custas', to='financeiro.grupocustas')),
                ('lancamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credito_custa', to='financeiro.lancamentofinanceiro')),
            ],
            options={
                'verbose_name': 'Custa Judicial',
                'verbose_name_plural': 'Custas Judiciais',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='MembroGrupoCustas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_custas', to='clientes.cliente')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='financeiro.grupocustas')),
            ],
            options={
                'verbose_name': 'Membro de grupo de custas',
                'verbose_name_plural': 'Membros de grupos de custas',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pagamento', 'Pagamento'), ('reembolso', 'Reembolso')], max_length=10)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('solicitada', 'Solicitada'), ('em_analise', 'Em análise'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('paga', 'Paga')], default='solicitada', max_length=20)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('data_gasto', models.DateField(blank=True, null=True)),
                ('anexo', models.FileField(storage=apps.saas_tenants.storage.StorageProtegido(), upload_to=apps.saas_tenants.storage.CaminhoArquivoTenant('protegido', 'financeiro/solicitacoes'))),
                ('observacao', models.TextField(blank=True)),
                ('pago_por', models.CharField(blank=True, choices=[('escritorio', 'Escritório'), ('cliente', 'Cliente')], max_length=12)),
                ('comprovante_pagamento', models.FileField(blank=True, null=True, storage=apps.saas_tenants.storage.StorageProtegido(), upload_to=apps.saas_tenants.storage.CaminhoArquivoTenant('protegido', 'financeiro/solicitacoes/comprovantes'))),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
                ('lancamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacao_origem', to='financeiro.lancamentofinanceiro')),
                ('pagamento_realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_pagas', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processos.processo')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_financeiras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação Financeira',
                'verbose_name_plural': 'Solicitações Financeiras',
                'ordering': ['-criado_em'],
            },
        ),
    ]
