# Generated by Django 5.2.15 on 2026-07-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lancamentofinanceiro',
            options={'ordering': ['data_vencimento', '-criado_em'], 'verbose_name': 'Lançamento Financeiro', 'verbose_name_plural': 'Lançamentos Financeiros'},
        ),
        migrations.RenameField(
            model_name='lancamentofinanceiro',
            old_name='data',
            new_name='data_vencimento',
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('pix', 'Pix'), ('boleto', 'Boleto'), ('transferencia', 'Transferência'), ('dinheiro', 'Dinheiro'), ('cartao', 'Cartão'), ('outro', 'Outro')], max_length=20),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='categoria',
            field=models.CharField(choices=[('honorario', 'Honorário'), ('exito', 'Honorário de Êxito'), ('reembolso', 'Reembolso'), ('custa_judicial', 'Custa Judicial'), ('diligencia', 'Diligência'), ('pericia', 'Perícia'), ('taxa', 'Taxa/Emolumento'), ('salario', 'Salário/Pró-labore'), ('aluguel', 'Aluguel'), ('software', 'Software/Assinatura'), ('imposto', 'Imposto'), ('despesa_escritorio', 'Despesa do Escritório'), ('outro', 'Outro')], default='honorario', max_length=30),
        ),
    ]
