# Generated by Django 5.2.15 on 2026-09-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='honorario',
            name='regime_pagamento',
            field=models.CharField(blank=True, choices=[('rpv', 'RPV'), ('precatorio', 'Precatório')], max_length=10),
        ),
    ]
