# Generated by Django 5.2.15 on 2026-09-23 23:56

import apps.saas_tenants.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_honorario_regime_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='honorario',
            name='documento',
            field=models.FileField(blank=True, null=True, storage=apps.saas_tenants.storage.StorageProtegido(), upload_to=apps.saas_tenants.storage.CaminhoArquivoTenant('protegido', 'financeiro/honorarios')),
        ),
    ]
