# Generated by Django 5.2.15 on 2026-09-02 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_cliente_responsavel_obrigatorio'),
        ('financeiro', '0002_ajustar_lancamento_financeiro'),
        ('processos', '0012_processo_integrantes_habilitados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='categoria',
            field=models.CharField(choices=[('honorario', 'Honorário'), ('exito', 'Honorário de Êxito'), ('reembolso', 'Reembolso'), ('solicitacao_pagamento', 'Solicitação de Pagamento'), ('custa_judicial', 'Custa Judicial'), ('diligencia', 'Diligência'), ('pericia', 'Perícia'), ('taxa', 'Taxa/Emolumento'), ('salario', 'Salário/Pró-labore'), ('aluguel', 'Aluguel'), ('software', 'Software/Assinatura'), ('imposto', 'Imposto'), ('despesa_escritorio', 'Despesa do Escritório'), ('outro', 'Outro')], default='honorario', max_length=30),
        ),
        migrations.CreateModel(
            name='SolicitacaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pagamento', 'Pagamento'), ('reembolso', 'Reembolso')], max_length=10)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('solicitada', 'Solicitada'), ('em_analise', 'Em análise'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('paga', 'Paga')], default='solicitada', max_length=20)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('data_gasto', models.DateField(blank=True, null=True)),
                ('anexo', models.FileField(upload_to='solicitacoes_financeiras/%Y/%m/')),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
                ('lancamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacao_origem', to='financeiro.lancamentofinanceiro')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processos.processo')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_financeiras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação Financeira',
                'verbose_name_plural': 'Solicitações Financeiras',
                'ordering': ['-criado_em'],
            },
        ),
    ]
