# Generated by Django 5.2.15 on 2026-09-03 13:11

import apps.saas_tenants.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_alter_lancamentofinanceiro_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaofinanceira',
            name='anexo',
            field=models.FileField(upload_to=apps.saas_tenants.storage.CaminhoArquivoTenant('protegido', 'financeiro/solicitacoes')),
        ),
    ]
