# Generated by Django 5.2.15 on 2026-09-03 13:33

import apps.saas_tenants.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_alter_solicitacaofinanceira_anexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaofinanceira',
            name='anexo',
            field=models.FileField(storage=apps.saas_tenants.storage.StorageProtegido(), upload_to=apps.saas_tenants.storage.CaminhoArquivoTenant('protegido', 'financeiro/solicitacoes')),
        ),
    ]
