# Generated by Django 5.2.15 on 2026-09-04 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_cliente_responsavel_obrigatorio'),
        ('financeiro', '0005_alter_solicitacaofinanceira_anexo'),
        ('processos', '0012_processo_integrantes_habilitados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Honorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('contratual', 'Contratual'), ('sucumbencial', 'Sucumbencial'), ('exito', 'Êxito'), ('outro', 'Outro')], max_length=20)),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_efetivo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('data_prevista', models.DateField(blank=True, null=True)),
                ('data_recebida', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('previsto', 'Previsto'), ('recebido', 'Recebido'), ('cancelado', 'Cancelado')], default='previsto', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processos.processo')),
            ],
            options={
                'verbose_name': 'Honorário',
                'verbose_name_plural': 'Honorários',
                'ordering': ['-criado_em'],
            },
        ),
    ]
