# Generated by Django 5.2.15 on 2026-09-13 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_honorario'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='classificacao',
            field=models.CharField(choices=[('unica', 'Única'), ('parcelado', 'Parcelado'), ('recorrente', 'Recorrente')], default='unica', max_length=12),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='duracao_data_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='duracao_quantidade',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='duracao_tipo',
            field=models.CharField(blank=True, choices=[('quantidade', 'Quantidade de ocorrências'), ('data_final', 'Data final'), ('indeterminado', 'Indeterminado')], max_length=15),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='lancamento_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='financeiro.lancamentofinanceiro'),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='numero_parcelas',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='periodicidade',
            field=models.CharField(blank=True, choices=[('mensal', 'Mensal'), ('anual', 'Anual')], max_length=10),
        ),
    ]
