# Generated by Django 5.2.15 on 2026-09-13 14:45

import apps.saas_tenants.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_lancamentofinanceiro_classificacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custajudicial',
            name='anexo',
            field=models.FileField(blank=True, null=True, storage=apps.saas_tenants.storage.StorageProtegido(), upload_to=apps.saas_tenants.storage.CaminhoArquivoTenant('protegido', 'financeiro/custas')),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='anexo',
            field=models.FileField(blank=True, null=True, storage=apps.saas_tenants.storage.StorageProtegido(), upload_to=apps.saas_tenants.storage.CaminhoArquivoTenant('protegido', 'financeiro/lancamentos')),
        ),
    ]
