# Generated by Django 5.2.15 on 2026-09-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_custajudicial_anexo_lancamentofinanceiro_anexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custajudicial',
            name='tipo',
            field=models.CharField(choices=[('adiantamento', 'Adiantado pelo escritório'), ('paga_pelo_cliente', 'Paga diretamente pelo cliente'), ('deposito_cliente', 'Depósito do cliente')], max_length=20),
        ),
    ]
