# Generated by Django 5.2.15 on 2026-09-13 15:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_alter_custajudicial_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='honorario',
            name='data_termo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='honorario',
            name='taxa_mensal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='honorario',
            name='valor_recebido',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
    ]
