# Generated by Django 5.2.15 on 2026-09-15 20:03

import apps.saas_tenants.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0010_honorario_data_termo_honorario_taxa_mensal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaofinanceira',
            name='comprovante_pagamento',
            field=models.FileField(blank=True, null=True, storage=apps.saas_tenants.storage.StorageProtegido(), upload_to=apps.saas_tenants.storage.CaminhoArquivoTenant('protegido', 'financeiro/solicitacoes/comprovantes')),
        ),
        migrations.AddField(
            model_name='solicitacaofinanceira',
            name='pago_por',
            field=models.CharField(blank=True, choices=[('escritorio', 'Escritório'), ('cliente', 'Cliente')], max_length=12),
        ),
    ]
