# Generated by Django 5.2.15 on 2026-09-19 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preencher_data_pagamento(apps, schema_editor):
    """Solicitações já pagas ganham a data do lançamento gerado no pagamento."""
    Solicitacao = apps.get_model("financeiro", "SolicitacaoFinanceira")
    for solicitacao in Solicitacao.objects.filter(
        status="paga", data_pagamento__isnull=True, lancamento__isnull=False,
    ).select_related("lancamento"):
        solicitacao.data_pagamento = solicitacao.lancamento.data_pagamento
        solicitacao.save(update_fields=["data_pagamento"])


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0011_solicitacaofinanceira_comprovante_pagamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='custajudicial',
            name='lancamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credito_custa', to='financeiro.lancamentofinanceiro'),
        ),
        migrations.AddField(
            model_name='custajudicial',
            name='reembolsada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reembolsa', to='financeiro.custajudicial'),
        ),
        migrations.AddField(
            model_name='solicitacaofinanceira',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaofinanceira',
            name='pagamento_realizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_pagas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(preencher_data_pagamento, migrations.RunPython.noop),
    ]
