# Generated by Django 5.2.15 on 2026-09-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0012_custa_credito_reembolso_pagamento_solicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='honorario',
            name='data_correcao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='honorario',
            name='data_juros',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='honorario',
            name='devedor_tipo',
            field=models.CharField(blank=True, choices=[('pessoa', 'Pessoa física ou jurídica'), ('ente_estatal', 'Ente estatal (União/Estado/Município)')], max_length=14),
        ),
        migrations.AddField(
            model_name='honorario',
            name='exito_data_correcao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='honorario',
            name='exito_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='honorario',
            name='exito_valor_ganho',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='honorario',
            name='forma_condenacao',
            field=models.CharField(blank=True, choices=[('percentual', 'Percentual sobre o valor da causa'), ('fixo', 'Valor fixo predeterminado')], max_length=12),
        ),
        migrations.AddField(
            model_name='honorario',
            name='indice_correcao',
            field=models.CharField(blank=True, choices=[('inpc', 'INPC (padrão legal)'), ('igpm', 'IGP-M (se previsto em contrato/sentença)'), ('selic', 'Taxa Selic (se previsto em contrato/sentença)')], max_length=6),
        ),
        migrations.AddField(
            model_name='honorario',
            name='percentual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='honorario',
            name='taxa_indice_mensal',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Taxa mensal (%) do índice escolhido, informada manualmente.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='honorario',
            name='valor_causa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='honorario',
            name='valor_fixo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
