# Generated by Django 5.2.15 on 2026-09-21 10:40

from django.db import migrations, models


def remapear_despesa_escritorio(apps, schema_editor):
    # "Despesa do Escritório" deixou de existir como categoria: vira "Outros".
    # As demais categorias antigas mantiveram a chave e só mudaram o rótulo.
    LancamentoFinanceiro = apps.get_model("financeiro", "LancamentoFinanceiro")
    LancamentoFinanceiro.objects.filter(categoria="despesa_escritorio").update(categoria="outro")


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0013_honorario_sucumbencial_calculado'),
    ]

    operations = [
        migrations.RunPython(remapear_despesa_escritorio, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='categoria',
            field=models.CharField(choices=[('honorario', 'Honorários'), ('honorario_sucumbencia', 'Honorários de sucumbência'), ('reembolso', 'Reembolso'), ('consultoria', 'Consultoria'), ('comissao', 'Comissão'), ('auditoria', 'Auditoria'), ('acordo', 'Acordo'), ('capacitacao', 'Capacitação'), ('aluguel', 'Aluguel'), ('condominio', 'Condomínio'), ('agua', 'Água'), ('luz', 'Luz'), ('internet', 'Internet'), ('salario', 'Salário'), ('bonificacao', 'Bonificação'), ('imposto', 'Impostos/taxas'), ('cursos', 'Cursos'), ('equipamentos', 'Equipamentos'), ('material', 'Material'), ('software', 'Software/assinatura'), ('outro', 'Outros'), ('exito', 'Honorário de Êxito'), ('solicitacao_pagamento', 'Solicitação de Pagamento'), ('custa_judicial', 'Custa Judicial'), ('diligencia', 'Diligência'), ('pericia', 'Perícia'), ('taxa', 'Taxa/Emolumento')], default='honorario', max_length=30),
        ),
    ]
