# Generated by Django 5.2.15 on 2026-09-21 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_nomes_e_localidade_em_maiusculas'),
        ('financeiro', '0014_categorias_lancamento_por_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoCustas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grupo de custas',
                'verbose_name_plural': 'Grupos de custas',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='custajudicial',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custas', to='financeiro.grupocustas'),
        ),
        migrations.CreateModel(
            name='MembroGrupoCustas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_custas', to='clientes.cliente')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='financeiro.grupocustas')),
            ],
            options={
                'verbose_name': 'Membro de grupo de custas',
                'verbose_name_plural': 'Membros de grupos de custas',
            },
        ),
    ]
