# Generated by Django 5.2.15 on 2026-09-21 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0015_custas_grupos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='honorario',
            old_name='valor_causa',
            new_name='valor_condenacao',
        ),
        migrations.AddField(
            model_name='honorario',
            name='classificacao',
            field=models.CharField(blank=True, choices=[('unica', 'Única'), ('parcelado', 'Parcelado'), ('recorrente', 'Recorrente')], max_length=12),
        ),
        migrations.AddField(
            model_name='honorario',
            name='data_correcao_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='honorario',
            name='data_juros_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='honorario',
            name='duracao_data_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='honorario',
            name='duracao_quantidade',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='honorario',
            name='duracao_tipo',
            field=models.CharField(blank=True, choices=[('quantidade', 'Quantidade de ocorrências'), ('data_final', 'Data final'), ('indeterminado', 'Indeterminado')], max_length=15),
        ),
        migrations.AddField(
            model_name='honorario',
            name='exito_base',
            field=models.CharField(blank=True, choices=[('ganho', 'Pelo ganho (atuo pelo autor/reconvindo)'), ('economia', 'Pela economia (atuo pelo réu)')], max_length=8),
        ),
        migrations.AddField(
            model_name='honorario',
            name='modalidade',
            field=models.CharField(blank=True, choices=[('valor', 'Valor'), ('exito', 'Por êxito'), ('valor_exito', 'Valor + êxito')], max_length=12),
        ),
        migrations.AddField(
            model_name='honorario',
            name='numero_parcelas',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='honorario',
            name='periodicidade',
            field=models.CharField(blank=True, choices=[('mensal', 'Mensal'), ('anual', 'Anual')], max_length=10),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='honorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='financeiro.honorario'),
        ),
        migrations.AlterField(
            model_name='honorario',
            name='forma_condenacao',
            field=models.CharField(blank=True, choices=[('fixo', 'Valor fixo'), ('percentual', 'Percentual sobre a condenação'), ('fixo_percentual', 'Valor fixo + percentual')], max_length=16),
        ),
        migrations.AlterField(
            model_name='honorario',
            name='indice_correcao',
            field=models.CharField(blank=True, choices=[('inpc', 'INPC (padrão legal)'), ('igpm', 'IGP-M (se previsto em contrato/sentença)'), ('selic', 'Taxa Selic (se previsto em contrato/sentença)'), ('ipca', 'IPCA (se previsto em contrato/sentença)')], max_length=6),
        ),
        migrations.AlterField(
            model_name='honorario',
            name='tipo',
            field=models.CharField(choices=[('contratual', 'Contratual'), ('sucumbencial', 'Sucumbência'), ('exito', 'Êxito'), ('outro', 'Outro')], max_length=20),
        ),
    ]
