# Generated by Django 5.2.15 on 2026-09-22 14:48

import apps.saas_tenants.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0016_honorarios_contratual_sucumbencia_ipca'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='comprovante_pagamento',
            field=models.FileField(blank=True, null=True, storage=apps.saas_tenants.storage.StorageProtegido(), upload_to=apps.saas_tenants.storage.CaminhoArquivoTenant('protegido', 'financeiro/lancamentos/comprovantes')),
        ),
    ]
