# Generated by Django 5.2.15 on 2026-09-22 19:23

import apps.modelos.models
import apps.saas_tenants.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaModeloPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria de Modelo de Peça',
                'verbose_name_plural': 'Categorias de Modelo de Peça',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EstiloEscritorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_estilo', models.CharField(choices=[('construir', 'Construir do zero'), ('anexar', 'Anexar peça existente')], default='construir', max_length=10)),
                ('arquivo_referencia', models.FileField(blank=True, help_text="Peça já formatada usada como referência visual (modo 'Anexar').", storage=apps.saas_tenants.storage.StorageProtegido(), upload_to=apps.saas_tenants.storage.CaminhoArquivoTenant('protegido', 'modelos/estilo/referencia'))),
                ('imagem_cabecalho', models.FileField(blank=True, storage=apps.saas_tenants.storage.StorageProtegido(), upload_to=apps.saas_tenants.storage.CaminhoArquivoTenant('protegido', 'modelos/estilo/cabecalho'))),
                ('imagem_rodape', models.FileField(blank=True, storage=apps.saas_tenants.storage.StorageProtegido(), upload_to=apps.saas_tenants.storage.CaminhoArquivoTenant('protegido', 'modelos/estilo/rodape'))),
                ('imagem_marca_dagua', models.FileField(blank=True, storage=apps.saas_tenants.storage.StorageProtegido(), upload_to=apps.saas_tenants.storage.CaminhoArquivoTenant('protegido', 'modelos/estilo/marca-dagua'))),
                ('config_documento', models.JSONField(default=apps.modelos.models.config_documento_padrao)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estilo do Escritório',
            },
        ),
        migrations.CreateModel(
            name='AssinaturaEstilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('modo', models.CharField(choices=[('texto', 'Texto'), ('imagem', 'Imagem')], default='texto', max_length=10)),
                ('texto', models.CharField(blank=True, max_length=300)),
                ('imagem', models.FileField(blank=True, storage=apps.saas_tenants.storage.StorageProtegido(), upload_to=apps.saas_tenants.storage.CaminhoArquivoTenant('protegido', 'modelos/estilo/assinaturas'))),
                ('largura', models.PositiveSmallIntegerField(default=30, help_text='Só vale em modo imagem.', verbose_name='Largura (% da folha)')),
                ('alinhamento', models.CharField(choices=[('left', 'Esquerda'), ('center', 'Centro'), ('right', 'Direita')], default='center', max_length=10)),
                ('estilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='modelos.estiloescritorio')),
            ],
            options={
                'verbose_name': 'Assinatura do Estilo',
                'verbose_name_plural': 'Assinaturas do Estilo',
                'ordering': ['ordem', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ModeloPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('area_direito', models.CharField(max_length=50)),
                ('conteudo', models.TextField(help_text='Conteúdo em texto ou HTML da peça modelo')),
                ('cabecalho_replicacao', models.CharField(choices=[('todas', 'Todas as páginas'), ('primeira', 'Apenas na primeira'), ('ultima', 'Apenas na última')], default='todas', max_length=10)),
                ('rodape_replicacao', models.CharField(choices=[('todas', 'Todas as páginas'), ('primeira', 'Apenas na primeira'), ('ultima', 'Apenas na última')], default='todas', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='modelos.categoriamodelopeca')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pecas_geradas', to='clientes.cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modelo de Peça',
                'verbose_name_plural': 'Modelos de Peças',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AnexoPecaGerada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(storage=apps.saas_tenants.storage.StorageProtegido(), upload_to=apps.saas_tenants.storage.CaminhoArquivoTenant('protegido', 'modelos/pecas-geradas'))),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='modelos.modelopeca')),
            ],
            options={
                'verbose_name': 'Anexo de peça gerada',
                'verbose_name_plural': 'Anexos de peças geradas',
                'ordering': ['enviado_em', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='VersaoModeloPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('area_direito', models.CharField(max_length=50)),
                ('conteudo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modelos.categoriamodelopeca')),
                ('editado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes', to='modelos.modelopeca')),
            ],
            options={
                'verbose_name': 'Versão de Modelo de Peça',
                'verbose_name_plural': 'Versões de Modelo de Peça',
                'ordering': ['-criado_em'],
            },
        ),
    ]
