# Generated by Django 5.2.15 on 2026-06-08 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstiloEscritorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tom_voz', models.TextField(blank=True, help_text='Descreva o tom de voz e estilo de escrita do escritório.')),
                ('instrucoes_gerais', models.TextField(blank=True, help_text='Instruções gerais que a IA deve seguir ao redigir peças.')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estilo do Escritório',
            },
        ),
        migrations.CreateModel(
            name='ModeloPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('categoria', models.CharField(help_text='Ex: Petição inicial, Contestação, Recurso', max_length=100)),
                ('area_direito', models.CharField(max_length=50)),
                ('conteudo', models.TextField(help_text='Conteúdo em texto ou HTML da peça modelo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modelo de Peça',
                'verbose_name_plural': 'Modelos de Peças',
                'ordering': ['-criado_em'],
            },
        ),
    ]
