# Generated by Django 5.2.15 on 2026-09-12 20:51

import apps.modelos.models
import apps.saas_tenants.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0003_versionamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='estiloescritorio',
            name='arquivo_referencia',
            field=models.FileField(blank=True, help_text="Peça já formatada usada como referência visual (modo 'Anexar').", storage=apps.saas_tenants.storage.StorageProtegido(), upload_to=apps.saas_tenants.storage.CaminhoArquivoTenant('protegido', 'modelos/estilo/referencia')),
        ),
        migrations.AddField(
            model_name='estiloescritorio',
            name='config_documento',
            field=models.JSONField(default=apps.modelos.models.config_documento_padrao),
        ),
        migrations.AddField(
            model_name='estiloescritorio',
            name='imagem_assinatura',
            field=models.FileField(blank=True, storage=apps.saas_tenants.storage.StorageProtegido(), upload_to=apps.saas_tenants.storage.CaminhoArquivoTenant('protegido', 'modelos/estilo/assinatura')),
        ),
        migrations.AddField(
            model_name='estiloescritorio',
            name='imagem_cabecalho',
            field=models.FileField(blank=True, storage=apps.saas_tenants.storage.StorageProtegido(), upload_to=apps.saas_tenants.storage.CaminhoArquivoTenant('protegido', 'modelos/estilo/cabecalho')),
        ),
        migrations.AddField(
            model_name='estiloescritorio',
            name='imagem_marca_dagua',
            field=models.FileField(blank=True, storage=apps.saas_tenants.storage.StorageProtegido(), upload_to=apps.saas_tenants.storage.CaminhoArquivoTenant('protegido', 'modelos/estilo/marca-dagua')),
        ),
        migrations.AddField(
            model_name='estiloescritorio',
            name='imagem_rodape',
            field=models.FileField(blank=True, storage=apps.saas_tenants.storage.StorageProtegido(), upload_to=apps.saas_tenants.storage.CaminhoArquivoTenant('protegido', 'modelos/estilo/rodape')),
        ),
        migrations.AddField(
            model_name='estiloescritorio',
            name='modo_estilo',
            field=models.CharField(choices=[('construir', 'Construir do zero'), ('anexar', 'Anexar peça existente')], default='construir', max_length=10),
        ),
    ]
