# Generated by Django 5.2.15 on 2026-09-18 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0006_seed_categorias_pre_definidas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estiloescritorio',
            name='instrucoes_gerais',
        ),
        migrations.RemoveField(
            model_name='estiloescritorio',
            name='tom_voz',
        ),
    ]
