# Generated by Django 5.2.15 on 2026-09-18 01:00
# Reordenado manualmente (specs/modelos-estilo-simplificacao-imagens.md):
# cria AssinaturaEstilo, porta o que já existia em
# imagem_assinatura/config_documento["slots"]["assinatura"] para lá, e só
# então remove o campo antigo — nesta ordem para não perder assinatura já
# configurada por um escritório.

import apps.saas_tenants.storage
import django.db.models.deletion
from django.db import migrations, models


def _backfill_slots_e_assinaturas(apps, schema_editor):
    EstiloEscritorio = apps.get_model("modelos", "EstiloEscritorio")
    AssinaturaEstilo = apps.get_model("modelos", "AssinaturaEstilo")

    for estilo in EstiloEscritorio.objects.all():
        config = estilo.config_documento or {}
        slots = config.get("slots", {})

        slot_assinatura = slots.pop("assinatura", None)
        if slot_assinatura and slot_assinatura.get("ativo") and (
            slot_assinatura.get("texto") or estilo.imagem_assinatura
        ):
            AssinaturaEstilo.objects.create(
                estilo=estilo,
                ordem=0,
                modo=slot_assinatura.get("modo", "texto"),
                texto=slot_assinatura.get("texto", "") if slot_assinatura.get("modo") != "imagem" else "",
                imagem=estilo.imagem_assinatura.name if estilo.imagem_assinatura else "",
                largura=30,
                alinhamento="center",
            )

        padroes_largura_alinhamento = {
            "cabecalho": {"largura": 30, "alinhamento": "center", "replicacao": "todas"},
            "rodape": {"largura": 30, "alinhamento": "center", "replicacao": "todas"},
            "marca_dagua": {"largura": 30, "alinhamento": "center"},
        }
        for nome, extras in padroes_largura_alinhamento.items():
            slot = slots.get(nome)
            if not isinstance(slot, dict):
                continue
            for chave, valor_padrao in extras.items():
                slot.setdefault(chave, valor_padrao)

        config["slots"] = slots
        estilo.config_documento = config
        estilo.save(update_fields=["config_documento"])


def _reverter_backfill(apps, schema_editor):
    # Puramente aditivo/organizacional — nada a desfazer com segurança
    # (a linha de AssinaturaEstilo já é removida pelo RemoveField/
    # DeleteModel reverso desta mesma migration).
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0007_remove_estiloescritorio_instrucoes_gerais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelopeca',
            name='cabecalho_replicacao',
            field=models.CharField(choices=[('todas', 'Todas as páginas'), ('primeira', 'Apenas na primeira'), ('ultima', 'Apenas na última')], default='todas', max_length=10),
        ),
        migrations.AddField(
            model_name='modelopeca',
            name='rodape_replicacao',
            field=models.CharField(choices=[('todas', 'Todas as páginas'), ('primeira', 'Apenas na primeira'), ('ultima', 'Apenas na última')], default='todas', max_length=10),
        ),
        migrations.CreateModel(
            name='AssinaturaEstilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('modo', models.CharField(choices=[('texto', 'Texto'), ('imagem', 'Imagem')], default='texto', max_length=10)),
                ('texto', models.CharField(blank=True, max_length=300)),
                ('imagem', models.FileField(blank=True, storage=apps.saas_tenants.storage.StorageProtegido(), upload_to=apps.saas_tenants.storage.CaminhoArquivoTenant('protegido', 'modelos/estilo/assinaturas'))),
                ('largura', models.PositiveSmallIntegerField(default=30, help_text='Só vale em modo imagem.', verbose_name='Largura (% da folha)')),
                ('alinhamento', models.CharField(choices=[('left', 'Esquerda'), ('center', 'Centro'), ('right', 'Direita')], default='center', max_length=10)),
                ('estilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='modelos.estiloescritorio')),
            ],
            options={
                'verbose_name': 'Assinatura do Estilo',
                'verbose_name_plural': 'Assinaturas do Estilo',
                'ordering': ['ordem', 'pk'],
            },
        ),
        migrations.RunPython(_backfill_slots_e_assinaturas, _reverter_backfill),
        migrations.RemoveField(
            model_name='estiloescritorio',
            name='imagem_assinatura',
        ),
    ]
