# Generated by Django 5.2.15 on 2026-09-19 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_cliente_data_nascimento'),
        ('modelos', '0008_remove_estiloescritorio_imagem_assinatura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelopeca',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pecas_geradas', to='clientes.cliente'),
        ),
    ]
