# Generated by Django 5.2.15 on 2026-09-19 23:06

import apps.saas_tenants.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0010_converter_area_eleitoral_para_outro'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoPecaGerada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(storage=apps.saas_tenants.storage.StorageProtegido(), upload_to=apps.saas_tenants.storage.CaminhoArquivoTenant('protegido', 'modelos/pecas-geradas'))),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='modelos.modelopeca')),
            ],
            options={
                'verbose_name': 'Anexo de peça gerada',
                'verbose_name_plural': 'Anexos de peças geradas',
                'ordering': ['enviado_em', 'pk'],
            },
        ),
    ]
