# Generated by Django 5.2.15 on 2026-09-18 00:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_delegacao_tarefas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='tarefas_participante', to=settings.AUTH_USER_MODEL, verbose_name='Participantes'),
        ),
    ]
