# Generated by Django 5.2.15 on 2026-09-22 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_convitedelegacao'),
        ('tarefas', '0004_tarefa_participantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='convite_delegacao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefa', to='accounts.convitedelegacao'),
        ),
    ]
