# Generated by Django 5.2.15 on 2026-06-08 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saas_tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco_mensal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('limite_processos', models.IntegerField(help_text='Número máximo de processos permitidos. 0 = ilimitado.')),
                ('limite_usuarios', models.IntegerField(help_text='Número máximo de usuários permitidos. 0 = ilimitado.')),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['preco_mensal'],
            },
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('suspenso', 'Suspenso'), ('cancelado', 'Cancelado')], default='ativo', max_length=20)),
                ('inicio', models.DateField()),
                ('proximo_vencimento', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('escritorio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='saas_tenants.escritorio')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saas_billing.plano')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
            },
        ),
    ]
