# Generated by Django 5.2.15 on 2026-09-22 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('clientes', '0001_initial'),
        ('processos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('audiencia', 'Audiência'), ('prazo', 'Prazo'), ('reuniao', 'Reunião'), ('protocolo', 'Protocolo'), ('pericia', 'Perícia'), ('julgamento', 'Julgamento'), ('retorno', 'Retorno'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='agendado', max_length=20)),
                ('dia_inteiro', models.BooleanField(default=False)),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField(blank=True, null=True)),
                ('local', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lembrete_enviado', models.BooleanField(default=False)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compromissos', to='clientes.cliente')),
                ('convite_delegacao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compromisso', to='accounts.convitedelegacao')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compromissos_criados', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compromissos', to='processos.processo')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compromissos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compromisso',
                'verbose_name_plural': 'Compromissos',
                'ordering': ['data_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ParticipanteCompromisso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('recusado', 'Recusado')], default='pendente', max_length=20)),
                ('lembrete_enviado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('compromisso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='agenda.compromisso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes_compromissos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participante do compromisso',
                'verbose_name_plural': 'Participantes do compromisso',
            },
        ),
        migrations.AddField(
            model_name='compromisso',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='compromissos_participando', through='agenda.ParticipanteCompromisso', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='participantecompromisso',
            constraint=models.UniqueConstraint(fields=('compromisso', 'usuario'), name='agenda_participante_unico_por_compromisso'),
        ),
    ]
