# Generated by Django 5.2.15 on 2026-07-01 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('clientes', '0002_cliente_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisso',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compromissos', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='compromisso',
            name='dia_inteiro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compromisso',
            name='status',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='agendado', max_length=20),
        ),
        migrations.AlterField(
            model_name='compromisso',
            name='tipo',
            field=models.CharField(choices=[('audiencia', 'Audiência'), ('prazo', 'Prazo'), ('reuniao', 'Reunião'), ('protocolo', 'Protocolo'), ('pericia', 'Perícia'), ('julgamento', 'Julgamento'), ('retorno', 'Retorno'), ('outro', 'Outro')], default='outro', max_length=20),
        ),
    ]
