# Generated by Django 5.2.15 on 2026-09-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_compromisso_cliente_compromisso_dia_inteiro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisso',
            name='lembrete_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
