# Generated by Django 5.2.15 on 2026-09-08 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_compromisso_lembrete_enviado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipanteCompromisso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('recusado', 'Recusado')], default='pendente', max_length=20)),
                ('lembrete_enviado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('compromisso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='agenda.compromisso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes_compromissos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participante do compromisso',
                'verbose_name_plural': 'Participantes do compromisso',
            },
        ),
        migrations.RemoveField(
            model_name='compromisso',
            name='participantes',
        ),
        migrations.AddField(
            model_name='compromisso',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='compromissos_participando', through='agenda.ParticipanteCompromisso', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='participantecompromisso',
            constraint=models.UniqueConstraint(fields=('compromisso', 'usuario'), name='agenda_participante_unico_por_compromisso'),
        ),
    ]
