# Generated by Django 5.2.15 on 2026-09-23 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_regras_natureza_e_remocao_tarefas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoItemAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('fatal_vespera', 'Véspera da data fatal'), ('fatal_hoje', 'Dia da data fatal'), ('para_fazer_vencida', 'Data para fazer vencida')], max_length=30)),
                ('referencia', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='agenda.itemagenda')),
            ],
            options={
                'verbose_name': 'Aviso de item da agenda',
                'verbose_name_plural': 'Avisos de item da agenda',
                'constraints': [models.UniqueConstraint(fields=('item', 'destinatario', 'motivo', 'referencia'), name='agenda_aviso_unico_por_motivo')],
            },
        ),
    ]
