# Generated by Django 5.2.15 on 2026-09-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_participantecompromisso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisso',
            name='cancelado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
