# Generated by Django 5.2.15 on 2026-09-22 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_convitedelegacao'),
        ('agenda', '0008_backfill_criado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisso',
            name='convite_delegacao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compromisso', to='accounts.convitedelegacao'),
        ),
    ]
