# Generated by Django 5.2.15 on 2026-09-22 19:23

import apps.saas_tenants.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('tipo', models.CharField(choices=[('individual', 'Individual'), ('grupo', 'Grupo'), ('global', 'Global')], default='individual', max_length=10)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('equipe', models.OneToOneField(blank=True, help_text='Grupo automático de uma Equipe — participantes sincronizados com os membros dela.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversa_grupo', to='accounts.equipe')),
                ('participantes', models.ManyToManyField(related_name='conversas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversa',
                'verbose_name_plural': 'Conversas',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='LeituraConversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lida_em', models.DateTimeField()),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='chat.conversa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras_conversas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leitura da conversa',
                'verbose_name_plural': 'Leituras da conversa',
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(blank=True)),
                ('anexo', models.FileField(blank=True, storage=apps.saas_tenants.storage.StorageProtegido(), upload_to=apps.saas_tenants.storage.CaminhoArquivoTenant('protegido', 'chat/mensagens'))),
                ('enviada_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='chat.conversa')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['enviada_em'],
            },
        ),
        migrations.AddConstraint(
            model_name='conversa',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'global')), fields=('tipo',), name='uniq_conversa_global'),
        ),
        migrations.AddConstraint(
            model_name='leituraconversa',
            constraint=models.UniqueConstraint(fields=('conversa', 'usuario'), name='chat_leitura_unica_por_usuario'),
        ),
    ]
