# Generated by Django 5.2.15 on 2026-07-25 18:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversa',
            name='tipo',
            field=models.CharField(choices=[('individual', 'Individual'), ('grupo', 'Grupo'), ('global', 'Global')], default='individual', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='conversa',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'global')), fields=('tipo',), name='uniq_conversa_global'),
        ),
    ]
