# Generated by Django 5.2.15 on 2026-09-09 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversa_global'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='lida',
        ),
        migrations.CreateModel(
            name='LeituraConversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lida_em', models.DateTimeField()),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='chat.conversa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras_conversas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leitura da conversa',
                'verbose_name_plural': 'Leituras da conversa',
                'constraints': [models.UniqueConstraint(fields=('conversa', 'usuario'), name='chat_leitura_unica_por_usuario')],
            },
        ),
    ]
