# Generated by Django 5.2.15 on 2026-09-09 18:02

import apps.saas_tenants.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_mensagem_lida_leituraconversa'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='anexo',
            field=models.FileField(blank=True, storage=apps.saas_tenants.storage.StorageProtegido(), upload_to=apps.saas_tenants.storage.CaminhoArquivoTenant('protegido', 'chat/mensagens')),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='conteudo',
            field=models.TextField(blank=True),
        ),
    ]
