# Generated by Django 5.2.15 on 2026-09-15 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_remove_habilitacaopapel_chk_habilitacaopapel_modulo_item_and_more'),
        ('chat', '0004_mensagem_anexo_alter_mensagem_conteudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversa',
            name='equipe',
            field=models.OneToOneField(blank=True, help_text='Grupo automático de uma Equipe — participantes sincronizados com os membros dela.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversa_grupo', to='accounts.equipe'),
        ),
    ]
